### ISSUE TITLE
多表格切换的时候，列的顺序错乱

### ISSUE THREAD

**Issue by Camphors** [nmxiaowei/avue#105]
avue官网的多表格切换时列的顺序错乱了，希望可以修复一下，附上一下地址https://avuejs.com/doc/crud/crud-change

**Comment by nmxiaowei** [comment]
没有复现

**Comment by Camphors** [comment]
有问题的呀，我现在看还是有问题，你仔细看，定义的列是【姓名】、【性别】，而第二个列表的顺序是【用户名】、【密码】、【姓名】，点击表头的【切换】按钮后第二个列表的顺序就变成了【姓名】、【用户名】、【密码】了

**Comment by rni-l** [comment]
> 有问题的呀，我现在看还是有问题，你仔细看，定义的列是【姓名】、【性别】，而第二个列表的顺序是【用户名】、【密码】、【姓名】，点击表头的【切换】按钮后第二个列表的顺序就变成了【姓名】、【用户名】、【密码】了

确实能重现。。。。
