### ISSUE TITLE
crud 动态显隐操作导致表格错位

### ISSUE THREAD

**Issue by cbf0713** [nmxiaowei/avue#108]
curd中的显隐按钮操作。将隐藏列显示出来后，表格错位。反过来将列隐藏，表格显示是正常的。
ele和avue已经升级到最新版。这个问题要怎么解决啊？
![image](https://user-images.githubusercontent.com/18612342/67262961-2eb1de00-f4d9-11e9-9770-14d3746ca3bf.png)
![image](https://user-images.githubusercontent.com/18612342/67262937-104be280-f4d9-11e9-84d0-9101c0cfc981.png)

**Comment by nmxiaowei** [comment]
下个版本修复
