### ISSUE TITLE
avue-crud组件搜索框的label通过searchLabelWidth设置无效

### ISSUE THREAD

**Issue by chenzongtian** [nmxiaowei/avue#110]
<img width="309" alt="WX20191031-114342@2x" src="https://user-images.githubusercontent.com/19252526/67917365-b8e1fc80-fbd3-11e9-9db3-2acdc7a72c79.png">

<img width="886" alt="WX20191031-113445@2x" src="https://user-images.githubusercontent.com/19252526/67917099-e7130c80-fbd2-11e9-9f80-2ebbd777b82f.png">

**Comment by nmxiaowei** [comment]
更新到最新版
