### ISSUE TITLE
crub使用搜索时配置option下的column，type为checkbox或radio时，渲染出来都是select

### ISSUE THREAD

**Issue by haoyanhong** [nmxiaowei/avue#118]
![image](https://user-images.githubusercontent.com/31054039/68647134-09ecdb80-0558-11ea-91a7-eff6b5883e08.png)
![image](https://user-images.githubusercontent.com/31054039/68647158-21c45f80-0558-11ea-8968-51667c5c1a05.png)

**Comment by nmxiaowei** [comment]
目前的定位都是select吗，如果需要修改，自行修改源码

**Comment by haoyanhong** [comment]
> 目前的定位都是select吗，如果需要修改，自行修改原始

![image](https://user-images.githubusercontent.com/31054039/68649459-bf6e5d80-055d-11ea-8709-54d9183fb11c.png)
![image](https://user-images.githubusercontent.com/31054039/68649464-c4cba800-055d-11ea-88d7-c7536d87e4ac.png)

那您有什么好的方法解决我现有的问题嘛，
我现在是这样，把checkbox的写在自定义的区域，但是他不自动排版，有一个空的不知道是为什么

**Comment by haoyanhong** [comment]
您好，打扰一下，目前针对这个问题您有什么好的解决方法嘛





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午2:45
收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送:&nbsp;"凉心@"<2624265785@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] crub使用搜索时配置option下的column，type为checkbox或radio时，渲染出来都是select (#118)




目前的定位都是select吗，如果需要修改，自行修改源码
