### ISSUE TITLE
使用crub 搜索区域如何配置

### ISSUE THREAD

**Issue by haoyanhong** [nmxiaowei/avue#119]
您好，前面马赛克部分是配置生成，后面三个checkbox是定义生成，我现在写到自定义区域，然后他没有自动排版，有一格空的，您能否帮忙解答
谢谢

![image](https://user-images.githubusercontent.com/31054039/68649861-a9ad6800-055e-11ea-9c08-59b331da3b42.png)
![image](https://user-images.githubusercontent.com/31054039/68649864-ac0fc200-055e-11ea-8996-d24672f5a628.png)

**Comment by nmxiaowei** [comment]
不支持
