### ISSUE TITLE
表单组件中使用富文本编辑器无法上传图片

### ISSUE THREAD

**Issue by zhixinpeng** [nmxiaowei/avue#120]
单独使用时，是可以的。
![image](https://user-images.githubusercontent.com/24643457/68861002-9b5d7880-0725-11ea-8fdc-efd3cd63eca7.png)
如果是在表单的配置项中
![image](https://user-images.githubusercontent.com/24643457/68861059-bc25ce00-0725-11ea-8508-be2a92f29a20.png)
则是不行的
![image](https://user-images.githubusercontent.com/24643457/68861087-c778f980-0725-11ea-95f3-f30def89b3c7.png)
请问是我配置项写错了吗，具体是哪里的问题呢

**Comment by nmxiaowei** [comment]
参考官网例子https://gitee.com/smallweigit/avue-plugin-ueditor

**Comment by zhixinpeng** [comment]
我参考了，就是和你例子一样的写法，还是不行呀。具体什么问题导致的能说明吗？
