### ISSUE TITLE
avue表格树无法正常显示

### ISSUE THREAD

**Issue by haoyanhong** [nmxiaowei/avue#126]
复制官网中的表格树例子，无法正常显示，麻烦大佬解答
![image](https://user-images.githubusercontent.com/31054039/69228623-dc8ad800-0bbe-11ea-9e9e-2d080b1cfe0b.png)

![image](https://user-images.githubusercontent.com/31054039/69228406-7a31d780-0bbe-11ea-8f76-63e5a916df4e.png)

**Comment by nmxiaowei** [comment]
更新到最新版本



---原始邮件---
发件人: "haoyanhong"<notifications@github.com&gt;
发送时间: 2019年11月20日(星期三) 下午5:55
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [nmxiaowei/avue] avue表格树无法正常显示 (#126)



复制官网中的表格树例子，无法正常显示，麻烦大佬解答

**Comment by haoyanhong** [comment]
更新为2.2.2还是不行，还需要改什么嘛






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午5:58
收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送:&nbsp;"凉心@"<2624265785@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] avue表格树无法正常显示 (#126)



更新到最新版本 
 
 
 
 ---原始邮件--- 
 发件人: "haoyanhong"<notifications@github.com&amp;gt; 
 发送时间: 2019年11月20日(星期三) 下午5:55 
 收件人: "nmxiaowei/avue"<avue@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [nmxiaowei/avue] avue表格树无法正常显示 (#126) 
 
 
 
 复制官网中的表格树例子，无法正常显示，麻烦大佬解答

**Comment by haoyanhong** [comment]
更新完以后还是不行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午5:58
收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送:&nbsp;"凉心@"<2624265785@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] avue表格树无法正常显示 (#126)



更新到最新版本 
 
 
 
 ---原始邮件--- 
 发件人: "haoyanhong"<notifications@github.com&amp;gt; 
 发送时间: 2019年11月20日(星期三) 下午5:55 
 收件人: "nmxiaowei/avue"<avue@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [nmxiaowei/avue] avue表格树无法正常显示 (#126) 
 
 
 
 复制官网中的表格树例子，无法正常显示，麻烦大佬解答

**Comment by haoyanhong** [comment]
![image](https://user-images.githubusercontent.com/31054039/69232164-7786b080-0bc5-11ea-9599-6077e91e2225.png)
![image](https://user-images.githubusercontent.com/31054039/69232171-79e90a80-0bc5-11ea-89af-05c8c4de8ad9.png)

**Comment by nmxiaowei** [comment]
rowKey配置了吗
