### ISSUE TITLE
[Feature Request] dicCallback

### ISSUE THREAD

**Issue by zzyyzz1992** [nmxiaowei/avue#129]
在表单组件中，比如有如下属性：
`column: [
          {
              label: "parent区域",
              prop: "parentArea",
              type: 'tree',
                remote: true,
                dicURL:"xxx",
              rules: [{
                required: true,
                message: "请输入上属区域名称",
                trigger: "blur"
              }]
            },
          ]
`
其中dicURL如果我想要使用带有权鉴的URL便很不友好。
希望能增加带有回调的版本，比如这样：
`
 remote: true,
 dicCallback: ()=>{ return await myRequest.requestDicData() },
`
甚至增加cachable选项：
`
 remote: true,
 dicCallback: ()=>{ return await myRequest.requestDicData() },
cachable: true,  //调用一次后存入缓存，不再加载
`

**Comment by nmxiaowei** [comment]
这个dicurl走的是你项目的axios，你可以在axios拦截器里去加相关东西
