### ISSUE TITLE
请问作者,2.2.2修复了什么?

### ISSUE THREAD

**Issue by zhuxianbin** [nmxiaowei/avue#132]
更新日志为:修复一个十分严肃的问题！！！
请问作者修复了什么?
机缘巧合,我们的测试说在项目中发现IE报严格模式的错误,我就尝试性的更新了一下升级到了2.2.3
发现IE的报错没有了,难道是这个?
但因为我之前用的是2.0.6,当时版本里,搜索区域还使用的是老布局,一旦升级后,就会有一些错乱,这还是已知的;
我们在之前更新avue版本时,会发现一些作者所提到的更新之外的一些改动,这方面说不好听的,有点糟糕
但也是为了作者能更加强大,产品更加稳定而言,本人非常看好作者的产品,加油~

**Comment by nmxiaowei** [comment]
搜索区域采用了form组件作为底层
