### ISSUE TITLE
树形选择器支持懒加载吗？

### ISSUE THREAD

**Issue by haoyanhong** [nmxiaowei/avue#134]
大佬，您好，树形选择器支持懒加载吗，要是不支持，有这方面的计划吗
![image](https://user-images.githubusercontent.com/31054039/69840441-80971200-1296-11ea-92a2-f53a49634e46.png)

**Comment by nmxiaowei** [comment]
表格树：https://avuejs.com/doc/new/crud-tree-lazy
选择框树https://avuejs.com/doc/new/from-tree-lazy
2.3.0版本扩展
