### ISSUE TITLE
type类型支持button嘛

### ISSUE THREAD

**Issue by haoyanhong** [nmxiaowei/avue#135]
大佬，您好，type目前是不支持button类型的，请问以后有这方面的更新计划嘛（另外，已帮您投票）
![image](https://user-images.githubusercontent.com/31054039/69840768-ab359a80-1297-11ea-836c-98725e2e9286.png)

**Comment by nmxiaowei** [comment]
button又不是表单里面必须的，如果你要用的话你可以采用自定义的方式

**Comment by haoyanhong** [comment]
怎么自定义，我自定义的话插不到对应的位置


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 上午9:32
收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送:&nbsp;"凉心@"<2624265785@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] type类型支持button嘛 (#135)




button又不是表单里面必须的，如果你要用的话你可以采用自定义的方式

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/form/form-slot
https://avuejs.com/doc/crud/crud-formslot
https://avuejs.com/doc/crud/crud-slot
