### ISSUE TITLE
我在package.json中配置的是2.2.0版本，为什么安装依赖后，2.3.0的部分能存在，如果表格的搜素区域

### ISSUE THREAD

**Issue by huangming19871105** [nmxiaowei/avue#145]

**Comment by huangming19871105** [comment]
表格的搜索区域，还有2.3.0如何自定义搜索输入框的文字

**Comment by lishangbu** [comment]
看看你```package.json```中的写法，如果是用```^2.2.0```那么拉的就是2.3.0的

**Comment by lishangbu** [comment]
> _No description provided._



> 表格的搜索区域，还有2.3.0如何自定义搜索输入框的文字

2.3.0的底层就是form组件，所以用法和form完全相同

**Comment by huangming19871105** [comment]
如何 把Avue的依赖固定在^2.2.0 我现在的项目都是在2.2.0版本的基础上写的，2.3.0的搜索配置与2.2.0的不一致， 如2.2.0 <template slot="search"></template>来自定义，而2.3.0需要<template slot-scope="scope" slot="sexSearch"></template>组合searchslot:true,来配置，并且只能自定义某个字段的 如'sex'，条件框前的文本（文字 如‘性别’，我不可以改成‘性别22222’）不能修改 
![image](https://user-images.githubusercontent.com/22408045/70770654-325f3400-1da9-11ea-8855-a14dd29b909d.png) ，尤其在一些字段分中英文的时候，要用一个条件框来搜索，实现不了。还有文档不是最新的

**Comment by lishangbu** [comment]
> 如何 把Avue的依赖固定在^2.2.0 我现在的项目都是在2.2.0版本的基础上写的，2.3.0的搜索配置与2.2.0的不一致， 如2.2.0 来自定义，而2.3.0需要组合searchslot:true,来配置，并且只能自定义某个字段的 如'sex'，条件框前的文本（文字 如‘性别’，我不可以改成‘性别22222’）不能修改
> ![image](https://user-images.githubusercontent.com/22408045/70770654-325f3400-1da9-11ea-8855-a14dd29b909d.png) ，尤其在一些字段分中英文的时候，要用一个条件框来搜索，实现不了。还有文档不是最新的

要么借助lock文件，要么简单粗暴点，直接定义版本为:
```json
"@smallwei/avue":"2.2.3"
```
然后删掉```node_modules```文件夹重新install一次就行

**Comment by nmxiaowei** [comment]
@lishangbu 正解
