### ISSUE TITLE
是否考虑可配置表单校验未通过时是否显示的红色圆圈×?

### ISSUE THREAD

**Issue by soulofduty** [nmxiaowei/avue#147]
![issue](https://user-images.githubusercontent.com/16477350/70765669-62510c00-1d96-11ea-9fe1-d35dce7f42ed.png)

修改源码19556行的status-icon的值可实现配置
![image](https://user-images.githubusercontent.com/16477350/70765911-2e2a1b00-1d97-11ea-9a5d-33f5c9824e58.png)
希望加入到官方修改中

**Comment by nmxiaowei** [comment]
目前不通过验证 是有红圈的
