### ISSUE TITLE
从地址栏中复制一个url链接，在新开一个浏览器标签页访问为404

### ISSUE THREAD

**Issue by haoyanhong** [nmxiaowei/avue#153]
在登录的状态下，从地址栏中复制一个url链接，在新开一个浏览器标签页访问直接跳到404页面（请大佬帮忙解答原因，谢谢谢谢）
![02eef1c84c4fcd2ab10f9aff6d0e748](https://user-images.githubusercontent.com/31054039/70982223-952a3580-20f1-11ea-9739-fffc3db81047.png)
![4d61d7de3577ba8cc37594780a3e6d0](https://user-images.githubusercontent.com/31054039/70982225-95c2cc00-20f1-11ea-8c44-703dc0e04d89.png)
![032f7004a6dd40e31479bc47e0b2844](https://user-images.githubusercontent.com/31054039/70982228-965b6280-20f1-11ea-81b7-4500ffde1e5f.png)

**Comment by nmxiaowei** [comment]
这是avue-cli的问题，这里是avue项目，请更改issues的项目
