### ISSUE TITLE
查询条件为时间类型的一些问题

### ISSUE THREAD

**Issue by 275401823** [nmxiaowei/avue#161]
1、当 type: "datetime" 弹出框只能选择日期，不能选择具体时间
2、当 type: 'datetimerange' 不生效
3、当 type: "month" 不生效

**Comment by nmxiaowei** [comment]
searchRange：true试下

**Comment by 275401823** [comment]
当设置 searchRange:true&nbsp; 宽度不够，如下图：

 &nbsp;
  
 &nbsp;
 &nbsp;
 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月25日(星期三) 下午3:39
 收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
 抄送:&nbsp;"し ω G "<275401823@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [nmxiaowei/avue] 查询条件为时间类型的一些问题 (#161)

 

 
searchRange：true试下

**Comment by nmxiaowei** [comment]
自己查看文档
