### ISSUE TITLE
框架及版本兼容问题

### ISSUE THREAD

**Issue by rcfeng** [nmxiaowei/avue#164]
我们的项目基于[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)搭建，后引入AVUE，目前主要使用AVUE的CRUD，目前开发的功能较少。

搭建环境后，出现一系列兼容问题。
- 1.抽屉无法打开：升级element-ui为^2.13.0版本后解决
- 2.table列显隐样式丢失：修改avue为2.0.6-2.1.5版本后解决
- 3.valueDefault属性不生效：修改avue为2.0.6-2.1.5版本后解决
- 4网络词典无法使用：报错 Cannot read property 'get' of undefined
![image](https://user-images.githubusercontent.com/39292626/71438005-df816700-272e-11ea-92bb-2bc27ace71b7.png)
这个问题我看了其他issue，均没有得到比较好的解决
avue2.3.3使用cds和npm分别安装过，无法解决第4个问题，并且会把问题2和问题3带出来
axios是有安装的，^0.18.0和^0.19.0都尝试过，无法解决问题
还看网上一些说法引入vue-resource等，都无法解决
- 5.还有很多细节问题，不过我觉得主要还是出在环境和框架兼容上，只要解决大体兼容问题，其他小问题都会消失

附件为我这边的package.json和main.js

[package.json.txt](https://github.com/nmxiaowei/avue/files/3999994/package.json.txt)
[main.js.txt](https://github.com/nmxiaowei/avue/files/3999995/main.js.txt)

**Comment by nmxiaowei** [comment]
1.升级到最新版的el使用el的抽屉
2.升级到最新版本解决
3.valueDefault和searchDefault变更为value和searchValue属性
4.需要在项目中引入axios，并且window.axios=axios挂载window下

**Comment by rcfeng** [comment]
![image](https://user-images.githubusercontent.com/39292626/71440333-caf59c80-2737-11ea-98ec-e701a724ba5a.png)
其他问题已解决，问题2未解决

**Comment by rcfeng** [comment]
问题4解决的代码为:
main.js加入
import axios from 'axios'
Vue.prototype.$axios = axios
window.axios = axios

**Comment by nmxiaowei** [comment]
详细说下2的问题

**Comment by rcfeng** [comment]
上图是当前效果  avue2.3.3

下图是理想效果 avue2.1.5
![image](https://user-images.githubusercontent.com/39292626/71440839-de096c00-2739-11ea-9ed9-f2ffd2a99c0f.png)

**Comment by rcfeng** [comment]
// columnBtn: false,
这段代码是注释掉的，用的框架默认值
目前的情况就是换个2.1.5的版本就能正常展示

**Comment by nmxiaowei** [comment]
新版本的交互方式改了，采用勾选的方式，当然你可以可以拖拽排序哦
https://avuejs.com/doc/crud/crud-column-sortable

**Comment by rcfeng** [comment]
ok，原来是正常的，我以为有问题的。

另外网络字典的文档描述是否可以写清楚一下,我分页查询的结构和词典查询的结构不一致,不知道如何把数据套进去
![image](https://user-images.githubusercontent.com/39292626/71441517-ba93f080-273c-11ea-8a51-64851e9d9a81.png)

分页查询结构:
`{"body":{"data":[{"sourceDatasource":"1207238669621432322","sourceDb":"test_archive"}],"pageCount":1,"totalRecord":1},"retCode":"0000","retMsg":"success"}`
词典查询结构:
{"body":[{"deleted":false,"id":"1","name":"1","type":1}],"retCode":"0000","retMsg":"success"}

**Comment by nmxiaowei** [comment]
这些问题文档都有，请去官网查看文档
