### ISSUE TITLE
表格组件中的搜索的按钮与输入框不同行

### ISSUE THREAD

**Issue by CaoMeiYouRen** [nmxiaowei/avue#169]
这是从官网截的图，所以别说是我自己的问题。
![mark](http://cdn.cmyr.ltd/blog/20191229/wyBqWkxRsnI5.png?imageslim)
浏览器配置截图
![mark](http://cdn.cmyr.ltd/blog/20191229/Tt6nL3lWU0eb.png?imageslim)
我看视频中的是在同一行的。
请问是有修改过吗？

**Comment by nmxiaowei** [comment]
请查看更新日志
