### ISSUE TITLE
搜索不支持自定义其他的了，只能用表格中的字段

### ISSUE THREAD

**Issue by 532133285** [nmxiaowei/avue#172]
这么改，以前做的项目都不能升级，升级就完了。

**Comment by nmxiaowei** [comment]
可以自己虚拟一个字段
完后设置为
hide:true
display:true
即可不出现在表格和表单中

**Comment by 532133285** [comment]
谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 下午3:35
收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送:&nbsp;"平平淡淡 才能细水长流"<532133285@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] 搜索不支持自定义其他的了，只能用表格中的字段 (#172)




可以自己虚拟一个字段
 完后设置为
 hide:true
 display:true
 即可不出现在表格和表单中
