### ISSUE TITLE
表格按钮显隐

### ISSUE THREAD

**Issue by 532133285** [nmxiaowei/avue#173]
表格使用字段header:false隐藏，如果这时缩小视图，适配的时候会把按钮全部显示出来，除非header的每个按钮单独设置为false。

**Comment by nmxiaowei** [comment]
说的详细一点

**Comment by 532133285** [comment]
表格顶部隐藏添加按钮，搜索按钮，刷新按钮，显隐按钮这么设置header: false;确实隐藏了。但是这时候如果不让浏览器全屏，然后拖动浏览器窗口，使其缩小。添​加按钮，搜索按钮，刷新按钮，显隐按钮就会出现，除非单独设置refreshBtn: false;searchBtn: false;columnBtn: false;addBtn: false;这么一来​设置header: false;就完全没有意义了​​。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 上午9:18
收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送:&nbsp;"平平淡淡 才能细水长流"<532133285@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] 表格按钮显隐 (#173)




说的详细一点

**Comment by nmxiaowei** [comment]
好的 我们排查下
