### ISSUE TITLE
框架没有做防xss攻击

### ISSUE THREAD

**Issue by 532133285** [nmxiaowei/avue#174]
表格渲染时能不能加层判断，formatter时用v-html，否则一律用v-text？现在全部都是v-html，根本不敢用了。项目已停，请给个答复，以便决定后面该怎么做。谢谢。

**Comment by nmxiaowei** [comment]
自行在axios拦截器里面过滤做xss
https://www.cnblogs.com/unclekeith/p/7750681.html

**Comment by vannel** [comment]
在avue-crud的表格里面，默认使用v-text不是更好吗？如果要显示html，可以单独用column slot实现。普遍来说，表格中还是v-text用的比较多吧？
