### ISSUE TITLE
日期时间选择器，在必填情况下选择验证出问题

### ISSUE THREAD

**Issue by wa-monster** [nmxiaowei/avue#176]
![image](https://user-images.githubusercontent.com/32135399/71960104-27c07f00-322f-11ea-9b4a-da6f876ca675.png)
日期时间选择器，在必填情况下选择验证出问题，就算有值也显示需要验证必填提示

**Comment by wa-monster** [comment]
代码
![image](https://user-images.githubusercontent.com/32135399/71960319-a9181180-322f-11ea-9eac-caeaccb61c3c.png)

**Comment by nmxiaowei** [comment]
哪一个版本

**Comment by wa-monster** [comment]
> 哪一个版本

2.2.3
![image](https://user-images.githubusercontent.com/32135399/72029626-7e769900-32c1-11ea-90b4-fa0558716cfd.png)

**Comment by nmxiaowei** [comment]
更新到最新版本试下

**Comment by wa-monster** [comment]
> 更新到最新版本试下
最新的没有问题了
