### ISSUE TITLE
type:tree,下拉列表选项多的情况，滚动条默认显示在最下方

### ISSUE THREAD

**Issue by 275401823** [nmxiaowei/avue#178]
v2.3.5版本更新后发现type:tree,下拉列表选项多的情况，滚动条默认显示在最下方，这样用户在选择的时候很不方面，需要拉到最上面才能看到筛选输入框，这个能处理下吗？

**Comment by nmxiaowei** [comment]
更新el版本到最新试试

**Comment by 275401823** [comment]
el已经是最新的2.13.0版本了
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年1月9日(星期四) 下午3:03
 收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
 抄送:&nbsp;"し ω G "<275401823@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [nmxiaowei/avue] type:tree,下拉列表选项多的情况，滚动条默认显示在最下方 (#178)

 

 
更新el版本到最新试试

**Comment by nmxiaowei** [comment]
发个图看看

**Comment by 275401823** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李鹏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 下午3:27
收件人:&nbsp;"nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送:&nbsp;"し ω G  "<275401823@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] type:tree,下拉列表选项多的情况，滚动条默认显示在最下方 (#178)




发个图看看

**Comment by nmxiaowei** [comment]
没有收到你的截图 直接从github传图

**Comment by 275401823** [comment]
![11111](https://user-images.githubusercontent.com/59189189/72237312-f66ff680-3614-11ea-93fc-43d4216b5b22.png)

**Comment by nmxiaowei** [comment]
2.5.0版本修复
