### ISSUE TITLE
后台快速开发模板Tab页签会打开多次，导致页面显示异常

### ISSUE THREAD

**Issue by snowiceyeah** [nmxiaowei/avue#183]
复现步骤：
1.点击官网
![image](https://user-images.githubusercontent.com/43429385/72590439-9fca2b80-3938-11ea-9073-75b4b7783044.png)
2.点击tab切换到首页
![image](https://user-images.githubusercontent.com/43429385/72590463-b2446500-3938-11ea-9755-5a20e32c1e41.png)
3.再点击官网tab页签
![image](https://user-images.githubusercontent.com/43429385/72590486-c38d7180-3938-11ea-8c95-2afc3adbe769.png)
4.页签会出现多个
![image](https://user-images.githubusercontent.com/43429385/72590500-cc7e4300-3938-11ea-9db0-a28fb4cdca09.png)
5.如果打开多个其他页签，然后再切回官网，会导致显示异常
![image](https://user-images.githubusercontent.com/43429385/72590533-ec156b80-3938-11ea-866c-543ead662cfa.png)

**Comment by Guanrui1** [comment]
![QQ图片20191012141951.gif](https://i.loli.net/2020/01/17/76zacOoAXfwTxYZ.gif)

**Comment by nmxiaowei** [comment]
此问题请提交到avue-cli项目下，不属于底层问题
