### ISSUE TITLE
新版本树形下拉选择，显示不完整

### ISSUE THREAD

**Issue by ouyangxiang** [nmxiaowei/avue#184]
新版本树形下拉选择，显示不完整

**Comment by ouyangxiang** [comment]
![下拉](https://user-images.githubusercontent.com/11919968/72701196-77853b80-3b89-11ea-9251-14d826f4d812.PNG)

**Comment by ouyangxiang** [comment]
截图如上，实际上还有很多节点。

**Comment by nmxiaowei** [comment]
更新到最新版本
