### ISSUE TITLE
dynamic里面嵌套自定义组件无效

### ISSUE THREAD

**Issue by wjxjasin** [nmxiaowei/avue#187]
dynamic里面嵌套自定义组件无效，有没有好的解决办法
代码如下：
{
                  label: '',
                  prop: 'dynamic',
                  type: 'dynamic',
                  children: {
                    align: 'center',
                    headerAlign: 'center',
                    column: [
                      {
                        label: '密码',
                        prop: 'password',
                        type: 'password',
                        formslot:true,
                        labelslot:true,
                        errorslot:true,
                      },
                    ]
                  }
                }

**Comment by nmxiaowei** [comment]
2.5.0版本
