### ISSUE TITLE
decimals这个接口应该是什么类型呢？

### ISSUE THREAD

**Issue by Guanrui1** [nmxiaowei/avue#188]
如题，官网说是Boolean
![QQ截图20200211121232.png](https://i.loli.net/2020/02/11/Qxmowz9Oq4J2kL5.png)
项目运行起来就一直报这个错误
![QQ截图20200211121336.png](https://i.loli.net/2020/02/11/thCYRlxduZaWBqi.png)
打开源码发现定义的是Number类型
![QQ截图20200211121324.png](https://i.loli.net/2020/02/11/pTVoAYldOWgbfum.png)

**Comment by nmxiaowei** [comment]
是number类型的  文档错误
