### ISSUE TITLE
建议替换掉流程图的组件

### ISSUE THREAD

**Issue by cmdares** [nmxiaowei/avue#191]
建议先仔细研究下 https://github.com/OXOYO/X-Flowchart-Vue
如果可行的化可将jsplumb 
替换成X-Flowchart-Vue  （vue+G6 图形引擎，且封装的相对完整，虽然当前G6不是最新版）
可以达到开箱即用的水平。
感谢。

**Comment by nmxiaowei** [comment]
暂时不考虑，可以自行集成项目
