### ISSUE TITLE
form里的多行输入，回车会触发submit

### ISSUE THREAD

**Issue by ansonhorse** [nmxiaowei/avue#196]
### avue版本
2.3.7

### 重现
column定义如下：
```
{
    label: '爱好',
    prop: 'ihow',
    type: 'textarea',
    minRows: 5
}
```

然后在textarea输入，按下回车键

### 现象
回车后，会触发submit事件，导致表单被提交

### 期望的处理
回车后，不触发submit事件

---

大概看了一下源码，不知道是不是跟这两个地方的处理有关：

https://github.com/nmxiaowei/avue/blob/bd85d2680196d6b271222cfc344fd89dfac9c3d5/packages/element-ui/form/index.vue#L83

https://github.com/nmxiaowei/avue/blob/bd85d2680196d6b271222cfc344fd89dfac9c3d5/packages/core/components/form/index.vue#L17

**Comment by nmxiaowei** [comment]
enter:false
更新到最新版

**Comment by ansonhorse** [comment]
哦确实，没仔细看下面的方法里的判断，谢谢了！

顺便提个建议：
如果有办法判断当前是textarea，就默认enter=false，也就是默认不开启回车提交，因为在textarea里回车提交，应该是个比较特殊的需求吧。
