### ISSUE TITLE
希望crud的分页可以更灵活一些

### ISSUE THREAD

**Issue by ansonhorse** [nmxiaowei/avue#197]
看到v2.4.0里，有这个变动：
> 修改crud分页逻辑，一页的时候不显示分页组件(/doc/crud/crud-open)

正常来说，这种设定是会让页面看起来更简洁。
不过也有一些体验上的缺失。
举个例子：如果分页大小很大，比如100，当记录总数有88时，如果不显示分页，就看不到记录数量。当然，开启索引列可以看到，但不一定都会开启的。

所以，个人感觉，应该可以有一个更灵活的处理。
比如说，分页选项里加一个`当只有一页时隐藏分页组件`的选项。

**Comment by nmxiaowei** [comment]
下个版本调整
