### ISSUE TITLE
nuxt 使用报错 window is not defined 

### ISSUE THREAD

**Issue by cheaprYang** [nmxiaowei/avue#201]
![image](https://user-images.githubusercontent.com/29188164/76708271-83781e80-6730-11ea-9a94-41a040b72780.png)

**Comment by nmxiaowei** [comment]
不支持nuxt

**Comment by cheaprYang** [comment]
老哥 可以支持一下吗？

**Comment by cheaprYang** [comment]
> 不支持nuxt

求支持，老哥
