### ISSUE TITLE
表单组件单选按钮，在必填情况下选择验证出问题

### ISSUE THREAD

**Issue by wa-monster** [nmxiaowei/avue#206]
表单组件单选按钮，在必填情况下选择验证出问题，第一次点击选中的时候会自动弹出验证失败
这是代码
![image](https://user-images.githubusercontent.com/32135399/77028768-c35f3000-69d4-11ea-808d-79280ed9ab6c.png)

这是效果
![image](https://user-images.githubusercontent.com/32135399/77028820-e7bb0c80-69d4-11ea-93c9-30fa14c42ee1.png)

目前使用的ban版本是 2.4.1
![image](https://user-images.githubusercontent.com/32135399/77028835-f43f6500-69d4-11ea-8e9a-29e3e08ee7f1.png)

**Comment by wa-monster** [comment]
"@smallwei/avue": "^2.4.1", 这是版本
 代码：
{
            label: "性别",
            prop: "sex",
            span: 6,
            type: "radio",
            dicData: [{
                label: '男',
                value: 0
            }, {
                label: '女',
                value: 1
            }],
            change:({value,column})=>{
                this.$message.success('change')
            },
            rules: [
              {
                required: true,
                message: "请选择性别",
                trigger: "change"
              }
            ]
         }

图传不上来 [/笑哭]

**Comment by shaokuuipo** [comment]
不光这个单选，下拉select也有一样的问题。

**Comment by nmxiaowei** [comment]
提供avue&nbsp;
ele
vue版本



---原始邮件---
发件人: "shaokuuipo"<notifications@github.com&gt;
发送时间: 2020年4月26日(周日) 上午9:04
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [nmxiaowei/avue] 表单组件单选按钮，在必填情况下选择验证出问题 (#206)




 
不光这个单选，下拉select也有一样的问题。

**Comment by lwl666666** [comment]
请问这个是怎么解决的

**Comment by wed1760617** [comment]
你好请问你解决了吗

**Comment by wed1760617** [comment]
> 表单组件单选按钮，在必填情况下选择验证出问题，第一次点击的时候会自动删除验证失败
> 这是代码
> ![图片](https://user-images.githubusercontent.com/32135399/77028768-c35f3000-69d4-11ea-808d-79280ed9ab6c.png)
> 
> 这是效果
> ![图片](https://user-images.githubusercontent.com/32135399/77028820-e7bb0c80-69d4-11ea-93c9-30fa14c42ee1.png)
> 
> 目前使用的ban版本是2.4.1
> ![图片](https://user-images.githubusercontent.com/32135399/77028835-f43f6500-69d4-11ea-8e9a-29e3e08ee7f1.png)

你好请问你是怎么解决得
