### ISSUE TITLE
avue-data-tabs的count属性不支持小数，会四舍五入，建议添加数据精度属性

### ISSUE THREAD

**Issue by wzg1101** [nmxiaowei/avue#209]
![image](https://user-images.githubusercontent.com/1169120/77279383-95dbf480-6cfc-11ea-99d2-30c26fd8907b.png)

![image](https://user-images.githubusercontent.com/1169120/77279419-abe9b500-6cfc-11ea-8367-962311728ef9.png)

![image](https://user-images.githubusercontent.com/1169120/77279245-4dbcd200-6cfc-11ea-9008-ddba3de626f0.png)

**Comment by nmxiaowei** [comment]
2.5.0+版本支持
