### ISSUE TITLE
“搜索自定义组件”无效

### ISSUE THREAD

**Issue by piaofei-li** [nmxiaowei/avue#210]
按照官网文档( https://avuejs.com/doc/crud/crud-search-slot )的步骤，完成之后组件无效果

![image](https://user-images.githubusercontent.com/39212658/77289627-4a821000-6d15-11ea-88e1-6561712bc1db.png)

![image](https://user-images.githubusercontent.com/39212658/77289752-8b7a2480-6d15-11ea-9712-00d123a9d7d7.png)

![image](https://user-images.githubusercontent.com/39212658/77289716-79988180-6d15-11ea-968c-bc7b133dc890.png)

**Comment by nmxiaowei** [comment]
用最新版本
