### ISSUE TITLE
路由配置问题

### ISSUE THREAD

**Issue by oyster111** [nmxiaowei/avue#213]
如何配置路由才能在打开新的标签页里面没有原来的layout组件，得到一个空白的页面

**Comment by nmxiaowei** [comment]
提交到avue-cli项目issues下

**Comment by oyster111** [comment]
> 提交到avue-cli项目issues下

能麻烦发个avue-cli项目issues的链接吗，在github上面没找到你的

**Comment by yujianquan** [comment]
avue-cli的项目地址我也懵了，我搜了一下有几个项目，而且一个issue都没有，请问一下你们是在哪儿维护的avue-cli呢，谢谢啦
