### ISSUE TITLE
更新数据时请求URL上的参数会被截断

### ISSUE THREAD

**Issue by leon-tang-cn** [nmxiaowei/avue#218]
"@smallwei/avue": "^2.5.0",

export const getUrlParams = (url) => {
  let result = {
    url: '',
    params: []
  };
  result.url = url.split('?')[0];
  if (url[1]) {
    let str = url[1];
    url = str.substr(1);
    let list = url.split('&');
    list.forEach(ele => {
      let dic = ele.split('=');
      let label = dic[0];
      let value = dic[1];
      result.params[label] = value;
    });
  }
  return result;
};
这里的url不是数组，而是字符串，这个处理逻辑是错的。

**Comment by nmxiaowei** [comment]
这个方法没有在组件里面调用啊

**Comment by nmxiaowei** [comment]
已经修复
// 获取url中的参数
export const getUrlParams = (url) => {
  let result = {
    url: '',
    params: {}
  };
  let list = url.split('?');
  result.url = list[0];
  let params = list[1];
  if (params) {
    let list = params.split('&');
    list.forEach(ele => {
      let dic = ele.split('=');
      let label = dic[0];
      let value = dic[1];
      result.params[label] = value;
    });
  }
  return result;
};
