### ISSUE TITLE
icon-select 中自己的iconfont图标无法正常显示

### ISSUE THREAD

**Issue by SilasDong** [nmxiaowei/avue#22]
无法正常显示，变成一个框框
```html
<i class="avue-crud-icon-select__icon icon-shuaxintongbu"></i> 
```
改成以下方式就可以了
```html
<i class=" icon-shuaxintongbu  avue-crud-icon-select__icon"></i>
```

动态修改 iconList 无法更新icon

**Comment by SilasDong** [comment]
无法正常显示，变成一个框框
<i class="avue-crud-icon-select__icon icon-shuaxintongbu"></i>
改成以下方式就可以了
<i class="icon-shuaxintongbu avue-crud-icon-select__icon"></i>

动态修改 iconList 中的值无法加载到icon

**Comment by nmxiaowei** [comment]
参考官网例子
https://avuex.avue.top/#/doc/form-icon-select
