### ISSUE TITLE
手机登录验证码倒计时出现负数

### ISSUE THREAD

**Issue by RavenHuo** [nmxiaowei/avue#220]
![image](https://user-images.githubusercontent.com/32315845/79126892-64be8380-7dd3-11ea-931d-e129a9aea563.png)
Default 其他组件->登录验证码组件。
倒计时只点击一次时不会出现异常问题。
但是当快速点击多次时，倒计时速度会增快且出现了负数

**Comment by nmxiaowei** [comment]
2.5.1版本修复
