### ISSUE TITLE
dicUrl,获取的数据如何在change事件中得到

### ISSUE THREAD

**Issue by FengZeming** [nmxiaowei/avue#222]
column: [{
          label: "下拉选择框",
          prop: "name",
          type: "select",
          dicUrl: '/list',
          props: {
            label: 'name',
            value: 'id'
          },
         change: v => {
                  想在change 事件 获取 dicUrl 获取的数据, 因为实现与旁边的input框的联动

                   数据:  [  
                                 {id: 1, name: "石桂英", state: "#f27999"},
                                  {id: 2, name: "崔磊", state: "#79bdf2"}
                             ]
                    要获取 state .    显示在旁边的input框
                     我想问如何能够获取到  这个下拉框的原始数据呢??

                  }
        }]

**Comment by nmxiaowei** [comment]
this.findObject方法找到对应的column，详情看2.5.0更新日志findObject用法

**Comment by MesmerizingXiaoSenSen** [comment]
谢谢
