### ISSUE TITLE
avue 版本2.4.1，自定义dialog，出现遮罩层

### ISSUE THREAD

**Issue by lamborpang** [nmxiaowei/avue#225]
表格上面增加一个批量增加的按钮
![1](https://user-images.githubusercontent.com/10228155/80441566-ba4f7000-893d-11ea-9480-b3cb776c1dc0.png)

点击批量增加，出现一个dialog，不应该先出现遮罩层。
![2](https://user-images.githubusercontent.com/10228155/80441575-bf142400-893d-11ea-941b-a15f06cb8eec.jpg)
需要怎么配置点《批量增加》，不要出现遮罩层？

**Comment by nmxiaowei** [comment]
dialog 添加append-to-body
