### ISSUE TITLE
怎么在table组件的搜索form中插入daterange的搜索条件

### ISSUE THREAD

**Issue by bigrain220** [nmxiaowei/avue#230]
Even i added the attribution type of daterange,it only showed the same effect of type by date!

**Comment by nmxiaowei** [comment]
searchRange:true



---原始邮件---
发件人: "William"<notifications@github.com&gt;
发送时间: 2020年5月6日(周三) 晚上11:41
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [nmxiaowei/avue] 怎么在table组件的搜索form中插入daterange的搜索条件 (#230)




 
Even i added the attribution type of daterange,it only showed the same effect of type by date!
