### ISSUE TITLE
表单中自定义按钮调用rowSave方法失败

### ISSUE THREAD

**Issue by oycmoycm** [nmxiaowei/avue#235]
按照文档，在CRUD的表单中，自定义了按钮，并绑定了click事件调用crud.rowSave方法，但是点击时控制台报错，代码和信息如下图。

![image](https://user-images.githubusercontent.com/65153348/81531925-25fdf800-9396-11ea-945a-62cdfa29d77f.png)

![image](https://user-images.githubusercontent.com/65153348/81531613-99ebd080-9395-11ea-912f-5be9bdaeaa39.png)
![image](https://user-images.githubusercontent.com/65153348/81531625-9f491b00-9395-11ea-94f7-3dbfc49d7a02.png)

**Comment by oycmoycm** [comment]
版本2.2.3

**Comment by oycmoycm** [comment]
已解决
this.$refs.crud.$refs.dialogForm.rowSave()可实现

**Comment by lioilLRM** [comment]
感谢，我是在父子表单，有父ref:crud和子ref:crud2，直接this.$refs.crud2.rowSave()保存也会出现楼主的这个错误。
后面通过楼主的方案this.$refs.crud.$refs.dialogForm.rowSave()可实现解决了。
