### ISSUE TITLE
crud组件查询面板中的“清空”问题

### ISSUE THREAD

**Issue by shaokuuipo** [nmxiaowei/avue#238]
当查询字段的type是daterange时，清空按钮无法清空已选择的日期数据。
报错信息：TypeError: e.split is not a function
avue版本：v2.5.2

**Comment by nmxiaowei** [comment]
` column: [{
            label: '日期',
            prop: 'datetime',
            type: 'daterange',
            search: true
          }]`

测试无法复现你说的这个情况

**Comment by shaokuuipo** [comment]
> ` column: [{ label: '日期', prop: 'datetime', type: 'daterange', search: true }]`
> 
> 测试无法复现你说的这个情况
@nmxiaowei 
我测试出来了，当设置valueFormat属性的时候，清空就会报错。把valueFormat属性删除就好了。需要重新开个issue吗？
