### ISSUE TITLE
vue+typescript 使用avue

### ISSUE THREAD

**Issue by ppzxc** [nmxiaowei/avue#248]
![image](https://user-images.githubusercontent.com/28623175/82520970-f9956900-9b57-11ea-9c24-517c6230807b.png)

import Avue from '@smallwei/avue'
import '@smallwei/avue/lib/index.css'
Vue.use(Avue)

报错

ERROR in E:/FF/untitled/src/main.ts
6:18 Could not find a declaration file for module '@smallwei/avue'. 'E:/FF/untitled/node_modules/@smallwei/avue/lib/avue.min.js' implicitly has an 'any' type.
  Try `npm install @types/smallwei__avue` if it exists or add a new declaration (.d.ts) file containing `declare module '@smallwei/avue';`

**Comment by nmxiaowei** [comment]
不支持typescript
