### ISSUE TITLE
打开行编辑 rowCell 后怎样对可编辑的列进行验证

### ISSUE THREAD

**Issue by 756924491** [nmxiaowei/avue#250]
使用行编辑后，表单验证不通过，表格行直接被锁死了不能操作。
![image](https://user-images.githubusercontent.com/46159649/82535198-1bebae80-9b79-11ea-8962-858805926131.png)

**Comment by nmxiaowei** [comment]
为了高效解决问题，请大家有技巧的使用issue，不按照格式提交的直接拒绝处理，感谢支持和理解

错误描述
提供必要的回显步骤。

异常日志
注意使用MD语法 日志 使用 ``格式化日志，越多详细越好

异常截图和代码
issue 支持直接粘贴
