### ISSUE TITLE
avue表格前端分页点几下就卡死了

### ISSUE THREAD

**Issue by JavaMrYang** [nmxiaowei/avue#252]
avue表格前端分页点几下就卡死了

**Comment by nmxiaowei** [comment]
为了高效解决问题，请大家有技巧的使用issue，不按照格式提交的直接拒绝处理，感谢支持和理解

错误描述
提供必要的回显步骤。

异常日志
注意使用MD语法 日志 使用 ``格式化日志，越多详细越好

异常截图和代码
issue 支持直接粘贴
