### ISSUE TITLE
2.5.0 之后的版本 table 组件中 的search 组件搜索按钮组样式问题

### ISSUE THREAD

**Issue by evemike** [nmxiaowei/avue#256]
按钮组类名 el-col el-col-10 avue-form__menu avue-form__menu--center
其中 col-10 的 width 样式被 avue-form__menu 中的 width 属性覆盖

**Comment by nmxiaowei** [comment]
2.5.3版本修复
2.5.0版本解决办法
```
.avue-form__menu{
	width:inherit
}
```
