### ISSUE TITLE
表单级联选择器选中之后选项不会自动隐藏，需要点一下其它地方才会隐藏

### ISSUE THREAD

**Issue by jabbawockeez** [nmxiaowei/avue#260]
如题，一下是我的配置：
formOption: {
        menuBtn: false,
        labelWidth: 0,
        gutter: 60,
        column: [
          {
            label:'',
            filterable: true,
            span: 8,
            prop:'business_path',
            type: "cascader",
            dicData: [],
            separator: " - ",
            placeholder: "请选择业务模块",
            changeOnSelect: true,
            checkStrictly: true,
            change:({value, column}) => {
                this.form.business_path = value[value.length - 1]
                this.handleBusinessSelect()
            },
          }
        ]
      }
官网demo https://avuejs.com/doc/form/form-cascader 里面选择任意一级后是会马上隐藏的，我这里却不行，请问哪里出了问题？

**Comment by nmxiaowei** [comment]
更新版本试试

**Comment by jabbawockeez** [comment]
> 更新版本试试

更新到2.6.0还不行，我在控制台发现有警告，会不会跟这个有关系呢？
![image](https://user-images.githubusercontent.com/5919100/83373882-76e49780-a3fc-11ea-8634-0e801cf1f218.png)

**Comment by Cookpoatoes** [comment]
级联选择器需要需要自动隐藏的话需要在级联上 加上 ref,然后再watch中监听改级联的绑定值，然后在wacth中
"form.applyOrgIds"() {
      if (this.$refs.checkOneDom) {
        this.$nextTick(() => {
          this.$refs.checkOneDom[0].dropDownVisible = false; //监听值发生变化就关闭它
        });
      }
    },

checkOneDom 就是你绑定在级联上的节点

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/form/form-display
