### ISSUE TITLE
avue 表格组件缓存 后返回会导致 列表错乱

### ISSUE THREAD

**Issue by Cookpoatoes** [nmxiaowei/avue#266]
列表组件是被缓存的，然后从其他页面返回后，列表中的高度重新计算了，导致表格高度错乱，在element中有方法doLayout重新渲染表格。但是在avue中该方法是一个 默认为true的值，请问如何在不刷新整个页面下，使avue的表格重新渲染

**Comment by nmxiaowei** [comment]
this.$refs.crud.doLayout()
重绘试试

**Comment by steptobe** [comment]
这问题为何关闭了
