### ISSUE TITLE
crud级联会导致请求暴增

### ISSUE THREAD

**Issue by AimLuo** [nmxiaowei/avue#269]
### 前提描述
设计有三级级联：**比如**省市区。
当设置hide为true时（默认也是true），每一行都单独为市和区发送请求。
一般默认一页十行，这就会**多出20条请求**，极大的浪费服务器以及客户端性能资源
### 问题描述
现在我要求服务端，将对应的名称返回，然后通过formatter或slot:true来展示，但此时还是会发送多余的请求，如何将这些请求去掉。

**Comment by nmxiaowei** [comment]
更新到最新版本即可

**Comment by AimLuo** [comment]
我暂时是通过在on-load中延迟设置dicUrl实现。
