### ISSUE TITLE
使用字典时经常匹配不到显示文字

### ISSUE THREAD

**Issue by AimLuo** [nmxiaowei/avue#270]
使用crud时：
字典的dicKey通常是string，数据库列表通常是number，导致经常匹配不上显示文字，设置dataType字段，有时候生效，有时候无效。搞得一脸懵逼。
建议加一个配置项来控制字典不做强制匹配，使用`==`即可。有时候去搞这个显示问题真是脑壳痛。

**Comment by uairain** [comment]
+1

**Comment by nmxiaowei** [comment]
如果长度超过13位 必须用字符串，js不支持这么大的精度
