### ISSUE TITLE
crud使用formatter展示时，保存获取不到对应的label

### ISSUE THREAD

**Issue by AimLuo** [nmxiaowei/avue#271]
如图：
![image](https://user-images.githubusercontent.com/21124342/84625075-20f01380-af15-11ea-8762-b60da26efe60.png)
保存时获取不到对应的$stationId

**Comment by AimLuo** [comment]
我暂时用slot来避免这个问题，但是这相当于画蛇添足

**Comment by nmxiaowei** [comment]
formatter(row, value label, column)

**Comment by nmxiaowei** [comment]
formatter(row, value label, column)
4个值

**Comment by AimLuo** [comment]
错了，不是这个意思。。。
type:select设置了formatter，当调用保存时：
```
    rowSave(row, done, loading) {
      const { $stationId} = row;
    // 这里获取不到$stationId
   }
```

**Comment by nmxiaowei** [comment]
是不配置了translate属性？如果配置了去掉

**Comment by AimLuo** [comment]
translate干嘛的，没有设置啊。等下，我写个例子

**Comment by nmxiaowei** [comment]
版本多少



---原始邮件---
发件人: "AimLuo"<notifications@github.com&gt;
发送时间: 2020年6月15日(周一) 下午2:58
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"李鹏伟"<nmxiaowei@vip.qq.com&gt;;
主题: Re: [nmxiaowei/avue] crud使用formatter展示时，保存获取不到对应的label (#271)




 
translate干嘛的，没有设置啊。等下，我写个例子

**Comment by AimLuo** [comment]
2.6.2

**Comment by AimLuo** [comment]
[代码在这](https://codesandbox.io/s/stupefied-edison-y2hz7?file=/src/components/HelloWorld.vue)
用了查询省市区的接口，有跨域，把HelloWorld.vue中的代码考出来本地调试。
以下是发现的问题：

1、保存时(rowSave)获取不到$相关数据
2、编辑和查看时，第三个级联(area)没有自动调用接口
3、新增时，第二个级联（city）改变，第三个级联（area）会调用两次
