### ISSUE TITLE
子表单 部分属性无效

### ISSUE THREAD

**Issue by nuan1989** [nmxiaowei/avue#272]
子表单
display: false,//无效
readonly:true,//无效
rules: [ { "required": true,"message": "单行文本必须填写" }] //验证无效
录制一个小视频https://enhancer.nos-eastchina1.126.net/1415018_cps.mp4

另外子表单的删除在移动端上面有点不好操作啊. 手指没按上去都不会显示. 建议默认一直显示删除按钮.

**Comment by nuan1989** [comment]
最新版本.当前版本 v2.6.2

**Comment by nmxiaowei** [comment]
更新2.6.14+版本
