### ISSUE TITLE
子表单添加插槽无效

### ISSUE THREAD

**Issue by huranLi** [nmxiaowei/avue#273]
{
            label: '子表单',
            prop: 'dynamic',
            type: 'dynamic',
            span:24,
            children: {
              align: 'center',
              headerAlign: 'center',
              rowAdd:(done)=>{
                this.$message.success('新增回调');
                  done({
                    input:'默认值'
                  });
              },
              rowDel:(row,done)=>{
                this.$message.success('删除回调'+JSON.stringify(row));
                done();
              },
              column: [{
                width: 200,
                label: '输入框',
                prop: "input",
                formslot: true,       **//这里的子表单插槽没效果欸**
              },

**Comment by nmxiaowei** [comment]
目前不支持
