### ISSUE TITLE
form switch 默认值无效

### ISSUE THREAD

**Issue by JieRenChen** [nmxiaowei/avue#274]
错误描述
form switch,编辑赋值的时候，switch没有变化

版本号
2.6.1

异常截图和代码
![image](https://user-images.githubusercontent.com/18524574/84650742-69222c80-af3b-11ea-84c3-3c8751dd3dad.png)
![image](https://user-images.githubusercontent.com/18524574/84650768-750dee80-af3b-11ea-9470-6a4816e2d390.png)

**Comment by nmxiaowei** [comment]
把字典反过来隐藏写到第一个
