### ISSUE TITLE
crud里的updateDic失效的问题

### ISSUE THREAD

**Issue by flymorn** [nmxiaowei/avue#276]
crud组件里的updateDic方法失效，测试版本：2.6.1  & 2.6.2

option里：
`option: {
        column: [
          {
            label: "分类",
            prop: "parent_id",
            type: "tree",
            defaultExpandAll: true,
            hide: true,
            props: {
              label: 'title',
              value: 'id'
            },
            dicUrl: `${this.baseUrl}/news_category/list`,
            search: false,
          },
]}`

在rowSave、rowUpdate 回调里执行：
`this.$refs.crud.updateDic('parent_id');`

视图页面里分类并没有发生变化。

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/sao

**Comment by flymorn** [comment]
骚操作里的

Object.assign(column, { dicData: dic });

是可以的，但是 updateDic 依然是失效的

**Comment by dongshixiao** [comment]
2.5.3版本同样报错
