### ISSUE TITLE
表格的page.currentPage没有双向绑定

### ISSUE THREAD

**Issue by zhangchao720** [nmxiaowei/avue#277]
1. 使用this.page.currentPage 不能够改变视图层
2. 点击视图层页码，也不能改变this.page.currentPage
使用方式遵循 :page.sync="page",
数据来自于服务端分页加载。
望排查修复此问题，版本v2.3.0

**Comment by nmxiaowei** [comment]
更新2.5.3+版本以上 可以双向绑定
