### ISSUE TITLE
建议字典值使用字符串，而不是纯数字。

### ISSUE THREAD

**Issue by shaokuuipo** [nmxiaowei/avue#280]
因为很多字典在使用国标的情况下会带有英文字母，或带有点，或带有中线，或以0开头，这些都是数字不能满足的。

**Comment by nmxiaowei** [comment]
字典是你后台返回的，和框架有啥关系

**Comment by shaokuuipo** [comment]
![ffff](https://user-images.githubusercontent.com/5934827/85353964-04b72c80-b53c-11ea-94ad-6ca52ad7ae74.png)
![ffff2](https://user-images.githubusercontent.com/5934827/85353968-0680f000-b53c-11ea-81cc-0cb6b1c9e762.png)

**Comment by shaokuuipo** [comment]
哦，对，发错地方了，😂😂😂
