### ISSUE TITLE
cascader级联选择器支持修改分隔符吗？

### ISSUE THREAD

**Issue by jabbawockeez** [nmxiaowei/avue#285]
如题，表单的级联选择器中有separator参数，不知道avue-cascader支持不？

**Comment by nmxiaowei** [comment]
支持

**Comment by jabbawockeez** [comment]
> 支持

请问有没有例子？在表单里是在column内设置分隔符的，换到avue-cascader，应该不会是先定义一个option，然后在里面在加个column这样的吧？我直接就在option里加seperator也没有效果
