### ISSUE TITLE
搜索列设置 type:''radio'  实际显示的是select下拉框  

### ISSUE THREAD

**Issue by lhtuling** [nmxiaowei/avue#289]
搜索列设置 type:''radio'  实际显示的是select下拉框  
![image](https://user-images.githubusercontent.com/44140500/86030232-ca331f80-ba66-11ea-88d2-fd4ed36bea41.png)

**Comment by lhtuling** [comment]
> 搜索列设置 type:''radio' 实际显示的是select下拉框
> ![image](https://user-images.githubusercontent.com/44140500/86030232-ca331f80-ba66-11ea-88d2-fd4ed36bea41.png)

其实不影响使用  是我理解错误  单选框用下拉列表做搜索 是ok的

**Comment by lhtuling** [comment]
> 搜索列设置 type:''radio' 实际显示的是select下拉框
> ![image](https://user-images.githubusercontent.com/44140500/86030232-ca331f80-ba66-11ea-88d2-fd4ed36bea41.png)

关了

**Comment by nmxiaowei** [comment]
是的这样子才符合搜索特性
