### ISSUE TITLE
表格表单的搜索和清空按钮不能控制吗？例如修改搜索按钮的文字、隐藏与显示按钮等

### ISSUE THREAD

**Issue by tagerwang** [nmxiaowei/avue#29]
对tabel表进行过滤查询时，单把某个字段配置search为true后，表格上方自动出现搜索、清空按钮，但我想把搜索改为查询，有API暴露出来吗？

**Comment by nmxiaowei** [comment]
暂时不可以，建议修改源码重新打包或则提供pr

**Comment by javascripth** [comment]
过几天我写个

**Comment by andersonguo** [comment]
> 对tabel表进行过滤查询时，单把某个字段配置search为true后，表格上方自动出现搜索、清空按钮，但我想把搜索改为查询，有API暴露出来吗？

看源码发现有个属性searchSubText可以用
