### ISSUE TITLE
avue-crud 表格组件 新增的表单 单选label 文本不显示问题？

### ISSUE THREAD

**Issue by panhai** [nmxiaowei/avue#297]
表格组件 新增的表单 单选label 文本不显示，{
    label: '状态',
    prop: 'state',
    type: 'radio',
    // search:true,
    // editDisabled: true,
    value:1, // 默认值
    dicData: [{
      label: '启用',
      value: 1
    }, {
      label: '禁用',
      value: 0
    }]
  }]
不显示 label 文本，只显示单选圆按钮

**Comment by nmxiaowei** [comment]
label:'',
labelWidth:1

**Comment by panhai** [comment]
回答不对哦。我需要的是显示dicData 里面的label 文本。你这个设置无效。
