### ISSUE TITLE
crud组件中的el-table可以添加selectable事件吗？

### ISSUE THREAD

**Issue by tagerwang** [nmxiaowei/avue#30]
crud组件中的el-table可以添加selectable事件吗，用来决定这一行的 CheckBox 是否可以勾选！

**Comment by rni-l** [comment]
[1.6.1](https://github.com/nmxiaowei/avue/releases/tag/v1.6.1) 版本 crud 加了 select 事件了

**Comment by tagerwang** [comment]
> [1.6.1](https://github.com/nmxiaowei/avue/releases/tag/v1.6.1) 版本 crud 加了 select 事件了

select事件和selectable列属性分别实现不同的功能：
select | 当用户手动勾选数据行的 Checkbox 时触发的事件
-- | --

selectable | 仅对 type=selection 的列有效，类型为 Function，Function 的返回值用来决定这一行的 CheckBox 是否可以勾选
-- | --

**Comment by rni-l** [comment]
> > [1.6.1](https://github.com/nmxiaowei/avue/releases/tag/v1.6.1) 版本 crud 加了 select 事件了
> 
> select事件和selectable列属性分别实现不同的功能：
> select | 当用户手动勾选数据行的 Checkbox 时触发的事件
> -- | --
> 
> selectable	仅对 type=selection 的列有效，类型为 Function，Function 的返回值用来决定这一行的 CheckBox 是否可以勾选

如果想快点更新，你可以提个 pr 给作者吧。。。这个项目更新好像不是很频繁

**Comment by nmxiaowei** [comment]
好的 下个版本合并
