### ISSUE TITLE
表格组件 新增的表单 单选label 文本不显示

### ISSUE THREAD

**Issue by panhai** [nmxiaowei/avue#301]
表格组件 新增的表单 单选label 文本不显示，{
label: '状态',
prop: 'state',
type: 'radio',
// search:true,
// editDisabled: true,
value:1, // 默认值
dicData: [{
label: '启用',
value: 1
}, {
label: '禁用',
value: 0
}]
}]
不显示  dicData 中的  label 文本，只显示单选圆按钮

**Comment by nmxiaowei** [comment]
截图看下
