### ISSUE TITLE
表格搜索时，当无数据时会分页选择器出现以下问题，

### ISSUE THREAD

**Issue by candebbs** [nmxiaowei/avue#302]
在表格中，我对特定条件进行搜索，后台返回无数据，但是前端页面样式问题，如图：
![微信图片_20200709170438](https://user-images.githubusercontent.com/3270728/87020533-8e3a5000-c206-11ea-9cba-5ae8b10e8df8.png)

最下面的分页选择器不对的，但是后台返回有数据，分页选择器是对的，我使用版本是2.6.10

**Comment by nmxiaowei** [comment]
搜索后，手动赋值分页的total

**Comment by candebbs** [comment]
我搜索成功后是手动设置了total。但问题后台有搜索数据返回来，分页选择器是对，但后台没有搜索数据返回来（这个数据是正常的），这时分页选择器是错的。

**Comment by candebbs** [comment]
> 搜索后，手动赋值分页的total

我搜索成功后是手动设置了total。但问题后台有搜索数据返回来，分页选择器是对，但后台没有搜索数据返回来（这个数据是正常的），这时分页选择器是错的。

**Comment by candebbs** [comment]
原来是 :page.sync="page"的问题
