### ISSUE TITLE
表格组件中上传问题 列type不能使用upload类型么  

### ISSUE THREAD

**Issue by lhtuling** [nmxiaowei/avue#303]
为啥文档上没有action  直接设置也不起效果

          {
            label: '干部回复附图',
            prop: 'imglist_a',
            loadText: '附件上传中，请稍等',
            span: 24,
            propsHttp: {
              res: "data",
              url: "link",
              name: "name",
            },
            tip: '只能上传jpg/png文件，且不超过500kb',
            accept: ['image/png', 'image/jpg', 'image/jpeg'],
            row: true,
            action: '/api/myoss/upload',
            slot: true,
            type: 'upload',
            span: 24,
            editDisplay: true,
          },

实际只有上传按钮 可以触发事件 但是并不能请求action的url
求解答!感谢!

**Comment by nmxiaowei** [comment]
window.axios=axios加了吗
