### ISSUE TITLE
dicQuery 使用字符串会报错 

### ISSUE THREAD

**Issue by carter911** [nmxiaowei/avue#304]
版本 2.6.10
问题： 使用dicUrl请求 但是dicQuery 使用JSON.stringify() 报错 建议兼容 虽然不影响使用但是会出现一堆错误
![image](https://user-images.githubusercontent.com/13519736/87135901-4e8a6b80-c2cd-11ea-8f04-7d6f29d7c201.png)
![image](https://user-images.githubusercontent.com/13519736/87136055-842f5480-c2cd-11ea-93a7-f01e21fc9cfe.png)

**Comment by nmxiaowei** [comment]
只能用对象
