### ISSUE TITLE
tree后面的操作栏如何判断显隐

### ISSUE THREAD

**Issue by Homebrew1** [nmxiaowei/avue#307]
![Uploading image.png…]()
根据当前栏位的名称能否让后面的三个点隐藏

**Comment by Homebrew1** [comment]
[一个三个卡槽,menuBtn,addBtn,-,都尝试了,但是取不到后面的三个点

**Comment by nmxiaowei** [comment]
目前不支持

**Comment by Homebrew1** [comment]
那可以把操作栏中的按钮都隐藏,写一个自定义按钮,控制自定义按钮的显隐吗

**Comment by uairain** [comment]
不要使用默认的按钮，把默认的按钮设置为false，例如:addBtn,editBtn等都隐藏掉，然后通过slot自定义按钮进去，这样就可以根据每一次的数据来进行判断是否要显示
![image](https://user-images.githubusercontent.com/12231348/88134292-d0a45980-cc16-11ea-988d-9d80563b0e86.png)

**Comment by uairain** [comment]
![image](https://user-images.githubusercontent.com/12231348/88134317-dac65800-cc16-11ea-9900-5280a989411a.png)

**Comment by Homebrew1** [comment]
已解决
