### ISSUE TITLE
lib中没有avue-antd.js

### ISSUE THREAD

**Issue by taojunnan** [nmxiaowei/avue#310]
`examples/antd/form/index.html`中`<script src="../../../lib/avue-antd.js"></script>`引入了`avue-antd.js`，但在`lib`目录没有此文件

**Comment by taojunnan** [comment]
@nmxiaowei 为什么这就close了

**Comment by nmxiaowei** [comment]
目前不做antd



---原始邮件---
发件人: "Junan"<notifications@github.com&gt;
发送时间: 2020年7月28日(周二) 上午10:05
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"李鹏伟"<nmxiaowei@vip.qq.com&gt;;
主题: Re: [nmxiaowei/avue] lib中没有avue-antd.js (#310)




 
@nmxiaowei 为什么这就close了
