### ISSUE TITLE
升级后2.6.9以后版本，icon-select组件变更为inputIcon组件

### ISSUE THREAD

**Issue by candebbs** [nmxiaowei/avue#311]
在2.6.9版本中，优化icon-select组件变更为inputIcon组件，我升级到2.6.9以后的版本，发现以前使用的阿里云图标显示不了，请问这个怎样解决？如图：
![微信图片_20200715094332](https://user-images.githubusercontent.com/3270728/87495094-1f844900-c683-11ea-979e-4c61355585d5.png)
和
![微信图片_20200715094300](https://user-images.githubusercontent.com/3270728/87495124-2dd26500-c683-11ea-8c77-dd4e2e710125.png)

在2.6.9以前版本可以正常显示的。
evn.js文件如下
```
// 配置编译环境和线上环境之间的切换

const env = process.env
const baseUrl = ''
// 图表库为avue和pig2套地址
const iconfontVersion = ['567566_qo5lxgtishg', '667895_v7uduh4zui']
const iconfontUrl = `//at.alicdn.com/t/font_$key.css`
const codeUrl = `${window.location.origin}/code`

export {
  baseUrl,
  iconfontUrl,
  iconfontVersion,
  codeUrl,
  env
}
```

**Comment by nmxiaowei** [comment]
优化icon-select组件变更为inputIcon组件在线例子
组件名字变更
https://avuejs.com/doc/component/input-icon
https://avuejs.com/doc/form/form-input-icon
