### ISSUE TITLE
Avue.js v2.6.11  老问题重现 datarange控件只能选一个日期了，范围没法选择

### ISSUE THREAD

**Issue by lhtuling** [nmxiaowei/avue#314]
https://gitee.com/smallweigit/avue/issues/I16LSL

**Comment by lhtuling** [comment]
切换到2.3.1  正常
2.6.11增加searchRange  无反应

**Comment by nmxiaowei** [comment]
例子正常
https://avuejs.com/doc/crud/crud-search
