### ISSUE TITLE
子表单验证，回显赋值后提交依然会提示验证信息，第二个子表单验证会报找不到children属性

### ISSUE THREAD

**Issue by wangxiGitHub** [nmxiaowei/avue#319]
版本： avue 2.6.12

1.子表单验证，开发详情页面时，回显赋值后，点提交依然会提示验证信息。
![image](https://user-images.githubusercontent.com/13217275/88033212-a9478100-cb71-11ea-806e-b324af187de1.png)

2.表单中有两个子表单，第二个子表单验证会报找不到children属性
![第二个子表单验证报错](https://user-images.githubusercontent.com/13217275/88033703-41456a80-cb72-11ea-8a79-cecb41373318.png)

**Comment by a-blue-l** [comment]
回显赋值之后依旧提示未填写的是如何解决的
