### ISSUE TITLE
avue多版本字典缺陷，字典缓存机制dicFlag导致无法正常加载

### ISSUE THREAD

**Issue by uairain** [nmxiaowei/avue#320]
1、
![image](https://user-images.githubusercontent.com/12231348/88133418-9df96180-cc14-11ea-9356-f4974f89c0de.png)
首次进入界面因为dicFlag非false可以进行获取，切换tag到组织首页，再次进入人员维护时无法获取字典，

经定位问题
![image](https://user-images.githubusercontent.com/12231348/88133517-db5def00-cc14-11ea-9b01-28061ab8e4f7.png)
发现为此处判断ele.dicFlag为false导致无法正常发起请求，考虑到由于加载过的字典在option.dicFlag = false中加了标识影响

最终定位到此处：
![image](https://user-images.githubusercontent.com/12231348/88133741-5fb07200-cc15-11ea-8b59-4222261781bc.png)

根据ele.dicFlag || option.dicFlag给列配置了dicFlag

但是option处进行了deepClone,下一行重新设值：option.column非使用deepClone导致引用类型出问题，下次进入时dicFlag为false

**Comment by nmxiaowei** [comment]
dicFlag属性去掉即可

**Comment by uairain** [comment]
我的配置里未进行配置dicFlag，是你内部处理获取后设置的，不是我外部传入的，因为你没有deepClone，导致修改了我最原始的option.建议我最好column也使用deepClone，避免污染

**Comment by uairain** [comment]
问题处的截图来源avue官方代码，非我工程的业务代码

**Comment by nmxiaowei** [comment]
ok了解
