### ISSUE TITLE
avue分页问题

### ISSUE THREAD

**Issue by uairain** [nmxiaowei/avue#321]
![image](https://user-images.githubusercontent.com/12231348/88138565-8627da80-cc20-11ea-9602-58c09a2b79c6.png)
此问题已经存在很久了，看到关闭的close里有这个，其实没有解决问题

![image](https://user-images.githubusercontent.com/12231348/88138763-e3239080-cc20-11ea-84e2-89ccb2323e8f.png)

注意我加载数据有6条，当我进行搜索后无数据传了page.total为0
但是defaultPage里面的total依然为上一次的6

原因在于：
![image](https://user-images.githubusercontent.com/12231348/88138782-f0d91600-cc20-11ea-9ed2-647125559064.png)
total: Number(this.page.total || this.defaultPage.total),
结就是total: Number( 0 || 6 )
total: 6

**Comment by nmxiaowei** [comment]
page.sync="page"
https://avuejs.com/doc/crud/crud-page

注意这个
