### ISSUE TITLE
表单验证当表单有两个表单，第二个子表单验证会报错

### ISSUE THREAD

**Issue by wangxiGitHub** [nmxiaowei/avue#326]
v: 2.6.12

当表单中有两个子表单，第一个子表单验证提醒是弹窗提醒，第二个子表单验证时会报：n promise) TypeError: Cannot set property 'children' of undefined
    at eval (avue.min.js?80d3:7)
    at Array.forEach (<anonymous>)
错误

![image](https://user-images.githubusercontent.com/13217275/88352438-53025a00-cd8c-11ea-8a91-3b194d04a338.png)

**Comment by nmxiaowei** [comment]
更新版本
