### ISSUE TITLE
分页器数据没有清空

### ISSUE THREAD

**Issue by Cookpoatoes** [nmxiaowei/avue#327]
在更新avue版本后，分页器数据0条不展示，只在第一次生效，后续如果筛选过后数据0条的话，分页器不会消失，而且会出现 分页器条数无法重置的问题，看了后续的更新版本也没有对这个进行处理，请问有什么方法可以处理这个问题？
![image](https://user-images.githubusercontent.com/32830503/88515462-514fc500-d01e-11ea-958d-57d93225a652.png)；经过筛选后
![image](https://user-images.githubusercontent.com/32830503/88515547-73494780-d01e-11ea-8a55-2609c1dc6569.png)

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/crud/crud-page
:page.sync="page"
