### ISSUE TITLE
avue-input-color 组件无法选择预置颜色的最后一个

### ISSUE THREAD

**Issue by PandaHeaven** [nmxiaowei/avue#330]
版本：v2.6.14
问题：avue-input-color 组件无法选择预置颜色的最后一个。官方文档的 “颜色选择器” 也有同样问题，以下为截图。
![image](https://user-images.githubusercontent.com/16608784/88780565-c1e11800-d1bd-11ea-9583-26eaa2600c91.png)

**Comment by nmxiaowei** [comment]
坐等el修复底层组件
