### ISSUE TITLE
avue-crud组件无法监听嵌套数组，如下。无法监听boby中的day1

### ISSUE THREAD

**Issue by daomiaru** [nmxiaowei/avue#332]
tabledata: [{
					age: 18,
					name: '儒',
					hoby: [{
						day1: 1
					}, {
						day2: 3
					}]
				}, {
					age: 25,
					name: '小芳',
					hoby: [{
						day6: 26
					}, {
						day9: 30
					}]
				}, {
					age: 19,
					name: '消防',
					hoby: [{
						day1: 24
					}, {
						day7: 30
					}]
				}]

**Comment by nmxiaowei** [comment]
只能监对象

**Comment by zhuwenbing** [comment]
> 只能监对象

```json
[{"id":1,"state":0,"order":{"name":"测试1"}},{"id":2,"state":1,"order":{"name":"测试2"}}]
```
那么请问对象如何获取？尝试 prop: 'order.name' 这种常规写法并不能获取！

**Comment by nmxiaowei** [comment]
bind 深结构绑定



---原始邮件---
发件人: "KissIce ***@***.***&gt;
发送时间: 2022年10月18日(周二) 下午4:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [nmxiaowei/avue] avue-crud组件无法监听嵌套数组，如下。无法监听boby中的day1 (#332)




  
只能监对象
  [{"id":1,"state":0,"order":{"name":"测试1"}},{"id":2,"state":1,"order":{"name":"测试2"}}]
 
那么请问对象如何获取？尝试 prop: 'order.name' 这种常规写法并不能获取！

**Comment by zhuwenbing** [comment]
> bind 深结构绑定
> […](#)
> ---原始邮件--- 发件人: "KissIce ***@***.***&gt; 发送时间: 2022年10月18日(周二) 下午4:01 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [nmxiaowei/avue] avue-crud组件无法监听嵌套数组，如下。无法监听boby中的day1 (#332) 只能监对象 [{"id":1,"state":0,"order":{"name":"测试1"}},{"id":2,"state":1,"order":{"name":"测试2"}}] 那么请问对象如何获取？尝试 prop: 'order.name' 这种常规写法并不能获取！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的。可以了！感谢！
