### ISSUE TITLE
辅助语不显示type: "number"

### ISSUE THREAD

**Issue by y-90** [nmxiaowei/avue#337]
append | 后面的辅助文字（当type为input））
-- | --
当type: "number",时，不显示辅助文字

**Comment by nmxiaowei** [comment]
![image](https://user-images.githubusercontent.com/35983068/89746314-975f5b00-daeb-11ea-8668-7d6b83101534.png)
![image](https://user-images.githubusercontent.com/35983068/89746320-9c240f00-daeb-11ea-93e2-f04d2ddd6103.png)
正常
