### ISSUE TITLE
自定义操作栏，未按照menuType=menu展示

### ISSUE THREAD

**Issue by y-90** [nmxiaowei/avue#346]
![image](https://user-images.githubusercontent.com/66720677/90461354-9e641a00-e138-11ea-9d2d-be1f342065a6.png)

如图所示，能否让自定义操作放入操作下拉中。。。。

**Comment by nmxiaowei** [comment]
<template slot-scope="scope" slot="menuBtn">
     <el-dropdown-item divided @click.native="tip">自定义按钮</el-dropdown-item>
  </template>

**Comment by y-90** [comment]
使用的就是自定义按钮。。。。查看、编辑、删除。在下拉中。。。

然而自定义按钮却没有在下拉中。。。。。明白。。。。
![image](https://user-images.githubusercontent.com/66720677/90465839-d1131000-e142-11ea-9499-fcf0e46b2079.png)

**Comment by y-90** [comment]
该问题，未得到解决。。。

使用的就是自定义按钮。&nbsp;&nbsp;


问题再次描述：
当操作栏展示为：menuType=menu 时。。。并没有放入下拉中。。。


原本的查看，编辑，删除操作在下拉中。。。


但是自定义按钮的，却没有在下拉中。。。。
