### ISSUE TITLE
Tab 启动后切换 关闭再启动 显示为上次 tab 而不是默认 tab

### ISSUE THREAD

**Issue by zhangsenhua** [nmxiaowei/avue#35]
tab 显示不正确，第一次打开 Tab，默认显示第一个，点击第二个 tab，然后关闭 Tab，再次打开 Tab，虽然内容是第一个 tab 的，但是 选中状态却是第二个的
![image](https://user-images.githubusercontent.com/19898809/56706426-839db300-6747-11e9-9ce4-c15717016a79.png)

**Comment by javascripth** [comment]
你好 经过您提供的描述进行测试无法还原你的情况。正常情况应该是默认显示上次你关闭时的tab标签页。
