### ISSUE TITLE
日期时区问题

### ISSUE THREAD

**Issue by huangyangcong** [nmxiaowei/avue#354]
format: 'yyyy-MM-dd HH:mm:ss',
valueFormat: 'yyyy-MM-ddTHH:mm:ssZ'
后端传值：2020-09-03T00:00:00Z
列表显示：2020-09-03 08:00:00
详情显示：2020-09-03 00:00:00

结果应该是：
后端传值：2020-09-03T00:00:00Z
列表显示：2020-09-03 08:00:00
**详情显示：2020-09-03 08:00:00**
**前端新增：2020-09-03 00:00:00 发送给后端：2020-09-02T16:00:00Z**

**Comment by nmxiaowei** [comment]
自行了解valueFormat的配置用法
https://element.eleme.cn/#/zh-CN/component/datetime-picker
