### ISSUE TITLE
请问怎么更改局部缓存的范围

### ISSUE THREAD

**Issue by guitarlong** [nmxiaowei/avue#355]
问题描述：目前切换tab时候，关闭后并不能刷新页面，看了下css文件样式是display:none
希望最终结果：切换的时候不刷新页面不清空搜索框，点击关闭后能够刷新整个页面
请问这个怎么更改keep-alive的作用范围
![图片](https://user-images.githubusercontent.com/58323946/92084022-61b34680-edf9-11ea-9d19-5794727cd433.png)
![图片](https://user-images.githubusercontent.com/58323946/92084063-70016280-edf9-11ea-90f4-472963239d0f.png)

**Comment by nmxiaowei** [comment]
https://gitee.com/smallweigit/avue-cli/blob/4cc560d0fa041611816b891ebd9bb1493ea82e9d/src/router/router.js
