### ISSUE TITLE
cascader选中某个节点后会在左上角出现不可消失的下拉框

### ISSUE THREAD

**Issue by jabbawockeez** [nmxiaowei/avue#364]
如图
![image](https://user-images.githubusercontent.com/5919100/92581222-f3232c80-f2c1-11ea-9e98-a99a742a3dc7.png)

另外还有个问题，我看代码里cascader的expandTrigger默认是hover了，然而我鼠标放上去并没有展开，还是得点击一下，即使我显式设置了这个属性也没有效果，请问这个是什么问题？

**Comment by nmxiaowei** [comment]
配置expandTrigger:hover
