### ISSUE TITLE
七牛上传无法动态指定文件名称问题？

### ISSUE THREAD

**Issue by bingxinti** [nmxiaowei/avue#365]
{
    label: '封面图',
    prop: 'coverPicture',
    type: 'upload',
    span: 24,
    data:{key:"ddd.png"},
    listType: 'picture-img',
    propsHttp: {
        url: "key"
    },
    oss: 'qiniu'
}

默认的 data里面的 key ddd.png有效，但是动态修改无效 （key 是七牛的文件名称）

这样子，怎么改本次都无效
 const coverPicture = this.findObject(this.option.column, "coverPicture");
                coverPicture.data = {key:"dwqdqdqd22.png"};
                column.data = {key:"dwqdqdqd.png"};
                console.log("uploadBefore1",coverPicture,this.option.column,column);
                console.log("uploadBefore2",file, done, loading);
                this.option.column[3].data = {key:"xxxxxx.png"};

上传参数
key: ddd.png
file: (binary)
token: 7v-2auf1SMlSora2Ac51F3toURcYMk587NeYrsTM:nYAI3QvBDEHGIVRHz9DXhiw5XZQ=:eyJzY29wZSI6Inl1bmtlLWNvbXBhbnkiLCJkZWFkbGluZSI6MTU5OTc4ODgxNjY5N30=

**Comment by bingxinti** [comment]
补充一下，我是在  uploadBefore(file, done, loading,column)   函数里面进行动态修改的
upload-before | 图片上传前的回调,会暂停图片上传function(file,done,loading)，done用于继续图片上传，loading用于中断操作

**Comment by nmxiaowei** [comment]
不支持
