### ISSUE TITLE
crud无法动态显隐

### ISSUE THREAD

**Issue by 2388786808** [nmxiaowei/avue#367]
错误描述
这个form的动态显隐，crud不生效？
![111](https://user-images.githubusercontent.com/61543759/93739211-572ae680-fc1a-11ea-9daa-101bfcd33788.png)
异常日志

版本号 
2.6.13

异常截图和代码

 
![2222](https://user-images.githubusercontent.com/61543759/93739656-62cadd00-fc1b-11ea-9450-4fd64a343221.png)

**Comment by nmxiaowei** [comment]
display 要提前写上
![image](https://user-images.githubusercontent.com/35983068/93750330-e2fa3e00-fc2d-11ea-8c03-36f8d012dbd9.png)
