### ISSUE TITLE
v2.4.1  关于 搜索框禁用状态 的疑问

### ISSUE THREAD

**Issue by night-ZK** [nmxiaowei/avue#372]
你好， 请问在 版本2.4.1 的 表格组件中， 我要怎么控制一个 搜索框 的禁用状态呢？
只能 用插槽的方式 自定义 搜索组件吗?  还是可以通过 某项属性类似于 input 的 disabled 来 实现呢？ 
翻了文档没找到 相关的 描述。
望告知，谢谢

**Comment by nmxiaowei** [comment]
<template slot-scope="{disabled,size}" slot="ageSearch">
     <el-input placeholder="自定义输入框" : disabled="disabled" :size="size" style="width:200px" v-model="search.age"></el-input>
  </template>
