### ISSUE TITLE
断网局域网内图标无法展示问题

### ISSUE THREAD

**Issue by qjws** [nmxiaowei/avue#378]
- 安全考虑项目只能内网使用,不能连接外网
- 部署后发现图标会报错; at.alicdn.com 访问不到;

请问 这种情况 有没有解决方案?

**Comment by qjws** [comment]
比如  这个 组件 avue-input-icon 点击后 是没有图标的

**Comment by nmxiaowei** [comment]
自行吧图标库下载到本地
