### ISSUE TITLE
:search.sync="search"修改search值，搜索框无变化

### ISSUE THREAD

**Issue by Homebrew1** [nmxiaowei/avue#383]
![image](https://user-images.githubusercontent.com/50045583/96663058-72f0ec00-1382-11eb-9264-af789b4fc468.png)
val是searchchange的参数值，赋值后，搜索框没有还原为上次搜素的值

**Comment by nmxiaowei** [comment]
this.$set方法赋值试试

**Comment by Homebrew1** [comment]
this.reset();
this.$set(this,"search",val);
console.log(this.search)；
试过了，无效，值已经附上去了，但是没有动

**Comment by Homebrew1** [comment]
这个search的代码在哪个位置，刚刚把项目下载了，让我看看怎么写的可以吗

**Comment by nmxiaowei** [comment]
用的啥版本 用2.6.17版本试试

**Comment by Homebrew1** [comment]
2.6.17是好的，但是出现了穿梭框，另外问一下这个地方是改的什么问题
![image](https://user-images.githubusercontent.com/50045583/96843911-6f905a00-1481-11eb-931f-8b0c8e502e17.png)

![image](https://user-images.githubusercontent.com/50045583/96843281-b762b180-1480-11eb-8417-c1855997fb1a.png)

**Comment by nmxiaowei** [comment]
avue用2.6.17 完后el版本用最新的

**Comment by Homebrew1** [comment]
element已升级到最新版本，但是穿梭框依然存在

**Comment by Homebrew1** [comment]
![image](https://user-images.githubusercontent.com/50045583/96943283-35b76600-150a-11eb-899e-0c075dfe0b56.png)
目前最新的是2.13.2

**Comment by nmxiaowei** [comment]
升级cdn目录下的ele

**Comment by nmxiaowei** [comment]
public/cdn/element-ui
