### ISSUE TITLE
在新的版本中出现很多的展开组件，如何去掉

### ISSUE THREAD

**Issue by Homebrew1** [nmxiaowei/avue#387]
![image](https://user-images.githubusercontent.com/50045583/96948573-9483dc00-1518-11eb-90b9-82ee612f4dc8.png)

**Comment by nmxiaowei** [comment]
检查样式 有一个全局样式覆盖了

**Comment by Homebrew1** [comment]
是的，去掉那个全局样式之后，还有些部分和旧版本不同，比如新增的下方多了一条横线，右边的icon没有对齐，是新版本变更了这些吗
![image](https://user-images.githubusercontent.com/50045583/96951434-10812280-151f-11eb-8bcd-ebc831994eaf.png)
![image](https://user-images.githubusercontent.com/50045583/96951475-21ca2f00-151f-11eb-9e6e-67665ad78aa3.png)

**Comment by nmxiaowei** [comment]
检查下样式吧 可能还有其他样式
