### ISSUE TITLE
表格 type=img 查看详情时第一张图片无法显示

### ISSUE THREAD

**Issue by qianwei1003** [nmxiaowei/avue#388]
表格 type=img 查看详情时第一张图片无法显示

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/crud/crud-url
参考例子

**Comment by qianwei1003** [comment]
我就是照着例子做的










------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李鹏伟"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 中午1:29
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;; 
抄送: "渣渣的钩子"<605974929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nmxiaowei/avue] 表格 type=img 查看详情时第一张图片无法显示 (#388)





 
https://avuejs.com/doc/crud/crud-url
 参考例子

**Comment by nmxiaowei** [comment]
什么版本

**Comment by qianwei1003** [comment]
2.6.18



---原始邮件---
发件人: "李鹏伟"<notifications@github.com&gt;
发送时间: 2020年10月28日(周三) 上午9:12
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送: "qianwei1003"<605974929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [nmxiaowei/avue] 表格 type=img 查看详情时第一张图片无法显示 (#388)




 
什么版本

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/crud/crud-url
例子完全没问题
