### ISSUE TITLE
在dialog中使用select选项定位有问题. 

### ISSUE THREAD

**Issue by yhuaqiang** [nmxiaowei/avue#390]
如果在弹出的dialog中使用select, 如果背景页面有滚动的话, 弹出的菜单项定位会不准,没有按照背景页面滚动适配
![image](https://user-images.githubusercontent.com/5283803/97513804-2c297480-19c8-11eb-9558-71a3ec7da62d.png)

**Comment by yhuaqiang** [comment]
https://6465-dev-read-pqakx-1300082696.tcb.qcloud.la/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20201029092539.png?sign=4d5761d5be43f66a9f434cfe6af7a789&t=1603934777

**Comment by nmxiaowei** [comment]
更新el版本，检查是否其它css样式覆盖

**Comment by yhuaqiang** [comment]
更新了最新版还是不行,是定位计算错误. top都是负值了
