### ISSUE TITLE
请问没有在搜素框下面的插槽吗

### ISSUE THREAD

**Issue by Homebrew1** [nmxiaowei/avue#391]
![image](https://user-images.githubusercontent.com/50045583/97531653-8f7acd00-19ef-11eb-9f28-ae5e49b5bf3c.png)

搜索按钮不能被放到上面吗,难道要重写搜索按钮 @nmxiaowei

**Comment by nmxiaowei** [comment]
```
<template slot="header" slot-scope="{}"></tepmplate>
```

试试这个卡槽
