### ISSUE TITLE
在dialog中使用select选项定位有问题,更新了最新版还是不行,是定位计算错误. top都是负值了 

### ISSUE THREAD

**Issue by yhuaqiang** [nmxiaowei/avue#392]
在dialog中使用select选项定位有问题,element-ui更新了最新版还是不行,是定位计算错误. top都是负值了

**Comment by yhuaqiang** [comment]
https://6465-dev-read-pqakx-1300082696.tcb.qcloud.la/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20201029092539.png?sign=4d5761d5be43f66a9f434cfe6af7a789&t=1603934777

**Comment by yhuaqiang** [comment]
问题好想喝avue-crud有关, 如果显示了搜索面板,定位就不行,关闭搜索面板,定位就对了

**Comment by yhuaqiang** [comment]
表格右上角的搜索按钮.

**Comment by nmxiaowei** [comment]
无法复现，检查下是不css冲突
