### ISSUE TITLE
功能性提问，想问一下，怎么实现部分行的数据禁用编辑和删除按钮，类似selectable这样的函数

### ISSUE THREAD

**Issue by mengyou658** [nmxiaowei/avue#402]
功能性提问，想问一下，怎么实现部分行的数据禁用编辑和删除按钮，类似selectable这样的函数
@linclin @xiaozehao @dongwenting @SunmChan @rni-l

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/crud/crud-permission

**Comment by mengyou658** [comment]
@nmxiaowei 谢谢
