### ISSUE TITLE
表单项太多，性能问题

### ISSUE THREAD

**Issue by liuht777** [nmxiaowei/avue#407]
1. 表单项太多，输入框打字都会卡顿
2. dictUrl 太多，发起几十个请求
3. 表单项太多，即使没有后端请求，加载速度都很慢很慢
4. 难道设计出来就是为了简单表单页面的吗

**Comment by nmxiaowei** [comment]
目前只能完成简单的表单页面

**Comment by xiangyuecn** [comment]
~ 真很优秀的一个框架，js简单的一个给表格数组赋值一下，底层的vue默默调用update一万下，这么大的功劳全部得归avue哦，卖的贵点也是应该的，毕竟都不是小学生了
