### ISSUE TITLE
表格组件-编辑本地数据时修改失败

### ISSUE THREAD

**Issue by ppengyi** [nmxiaowei/avue#409]
错误描述
表格组件的按钮修改方法,编辑其他行数据时候保存时却修改到了第一行数据,被修改行却没有被更改

问题复现
官网示例表格组件->按钮方法->修改李四数据->张三的数据被修改

异常日志
无

版本号
v2.7.4

异常截图和代码
![image](https://user-images.githubusercontent.com/34240593/102055379-c2edab80-3e25-11eb-8ab1-a69e5e112c99.png)
![image](https://user-images.githubusercontent.com/34240593/102055443-d9940280-3e25-11eb-9d0e-118bd876c894.png)
![image](https://user-images.githubusercontent.com/34240593/102055563-03e5c000-3e26-11eb-9e09-966995b61a90.png)

**Comment by nmxiaowei** [comment]
传入`done`函数修改数据，需要指定主键`rowKey`

例子已经完善
https://avuejs.com/doc/crud/crud-fun
