### ISSUE TITLE
表单初始化 问题

### ISSUE THREAD

**Issue by z363416071** [nmxiaowei/avue#413]
![image](https://user-images.githubusercontent.com/64683397/102688938-5ca5c600-4235-11eb-8c32-fefcc4ac5fbc.png)

表格,对于display=false,type = upload的数据 ,设置dataType = string无效,设置value = '' 也无效,会造成提交仍然传递该数据,并且为[],

**Comment by nmxiaowei** [comment]
版本多少

**Comment by z363416071** [comment]
版本:2.7.4

**Comment by nmxiaowei** [comment]
![image](https://user-images.githubusercontent.com/35983068/102749320-cdb4bd00-439e-11eb-81a2-94cd898d3d82.png)
本身就是string 不需要配置dataType

**Comment by z363416071** [comment]
<template >
    <avue-form v-model = "form" :option = "option" @submit = "submit" ref = "invalidReasonForm" >
    </avue-form >
</template >
<script >


export default {
    data() {
        return {
            form: {},
            option: {
                column: [
                    {
                        label: "编码",
                        prop:"code",
                        type: "input",
                    },
                    {
                        label: "营业执照",
                        prop: "licensePic",
                        dataType: "string",
                        type: "upload",
                        listType: "picture-img",
                        propsHttp: {
                            home: this.$store.state.project.ossDomain?.requestPath,
                            res: "data",
                            url: "link"
                        },
                        value:'',
                        display: false
                    },
                ]
            },
        };
    },
    methods: {
        submit(from,done) {
            console.log(from)
            done()
        }
    },
};
</script >


licensePic默认初始化数组,并不是string

**Comment by z363416071** [comment]
可以进行测试
