### ISSUE TITLE
旧的文档建议保留一份，方便查询

### ISSUE THREAD

**Issue by jabbawockeez** [nmxiaowei/avue#415]
avue版本更新迭代太快了，我们项目中使用的avue不可能每次都跟上最新版本，所以文档也希望能每个版本都保留一份，能够满足不同开发者的需求

**Comment by nmxiaowei** [comment]
好的 我们后期会考虑的

**Comment by MeichaoWen** [comment]
>  好的我们后续会考虑的

我觉得可以参考 elemetUI的官网，不同版本对应不同的文档。
