### ISSUE TITLE
附件上传后，删除，再重新上传又出现

### ISSUE THREAD

**Issue by chinawind** [nmxiaowei/avue#419]
附件上传后，删除，再重新上传又出现

**Comment by chinawind** [comment]
附件上传限制1个，再次上传应该替换

**Comment by nmxiaowei** [comment]
啥版本

**Comment by chinawind** [comment]
2.6.18



在 2021-01-07 08:45:31，"李鹏伟" <notifications@github.com> 写道：

啥版本

**Comment by chinawind** [comment]
"@smallwei/avue": "^2.7.5" 这个版本问题有依旧， uploadDelete 里做删除才可以。 this.$refs.crud.tableForm.filePath 做删除后重新赋值可以解决问题，但这样太麻烦了。



在 2021-01-07 08:45:31，"李鹏伟" <notifications@github.com> 写道：

啥版本

**Comment by nmxiaowei** [comment]
发一下你的option
