### ISSUE TITLE
crud组件中的弹窗问题

### ISSUE THREAD

**Issue by shaokuuipo** [nmxiaowei/avue#421]
想要固定弹窗的高度，当弹窗的内容超出的情况下，只滚动中间内容部分。title和下面按钮保持不动。
请问怎么才能做到这个需求呢？

**Comment by nmxiaowei** [comment]
dialogHeight:300

**Comment by shaokuuipo** [comment]
大哥，我知道怎么设置高度！你是没明白我的意思啊。。。

**Comment by shaokuuipo** [comment]
> dialogHeight:300

大哥，我知道怎么设置高度！你是没明白我的意思啊。。。
