### ISSUE TITLE
表单组件单选按钮，在必填情况下选择验证出问题 

### ISSUE THREAD

**Issue by wed1760617** [nmxiaowei/avue#423]

**Comment by nmxiaowei** [comment]
上代码啊

**Comment by wed1760617** [comment]
> 上代码啊
`    {
      "type": "radio",
      "label": "工单优先级",
      "dicData": [
        {
          "label": "低",
          "value": 0
        },
        {
          "label": "一般",
          "value": 1
        },
        {
          "label": "紧急",
          "value": 2
        },
        {
          "label": "非常紧急",
          "value": "3"
        }
      ],
      "span": 24,
      "display": true,
      "prop": "workLevel",
      "required": true,
      "rules": [
        {
          "required": true,
          "message": "请选择工单优先级"
        }
      ],
      "valueDefault": "",
      "disabled": false,
      "border": false
    },`
![image](https://user-images.githubusercontent.com/60960984/105430875-7fd9f000-5c8f-11eb-9f66-9268cd8b351c.png)

**Comment by wed1760617** [comment]
> 上代码啊

这是拖拽生成得工单模板,只有这个验证代码

**Comment by wed1760617** [comment]
> 上代码啊

第一次点击单选按钮已经选中时,会出现验证信息,之后的点击不会

**Comment by wed1760617** [comment]
> 上代码啊

已解决,bug版本2.4.1,升级到最新版本就好了
