### ISSUE TITLE
option column 页面已经渲染后，再次通过js修改不起作用

### ISSUE THREAD

**Issue by ouDongSheng** [nmxiaowei/avue#424]
this.findObject(this.editoption.column,'pname').hide=true;
        this.findObject(this.editoption.column,'isSingle').hide=true;
        this.findObject(this.editoption.column,'reason').hide=true;
        this.findObject(this.editoption.column,'updateTime').hide=true;
        this.findObject(this.editoption.column,'realName').hide=true;

**Comment by nmxiaowei** [comment]
提前吧hide属性写到column中
