### ISSUE TITLE
avue-crud组件自定义search插槽无法显示

### ISSUE THREAD

**Issue by yunfeihuang** [nmxiaowei/avue#426]

**Comment by yunfeihuang** [comment]
<avue-crud ref="crud"
                       :page="page"
                       :data="tableData"
                       :permission="permissionList"
                       :table-loading="tableLoading"
                       :option="tableOption"
                       @on-load="getList"
                       @search-change="searchChange"
                       @refresh-change="refreshChange"
                       @size-change="sizeChange"
                       @current-change="currentChange"
                       @search-reset = "resetChange"
                       :show-column.sync="showColumn">

                <template slot="search">
                    <el-form-item label="操作日期">
                        <el-date-picker v-model="searchForm.startDate" type="date" placeholder="操作开始日期" value-format="yyyy-MM-dd" format="yyyy-MM-dd"></el-date-picker>
                    </el-form-item>
                    <el-form-item label="">
                        <span class="date_end">至</span>
                        <el-date-picker v-model="searchForm.endDate" type="date" placeholder="操作结束日期" value-format="yyyy-MM-dd" format="yyyy-MM-dd"></el-date-picker>
                    </el-form-item>

                    <el-form-item label="操作人">
                        <el-input placeholder="操作人" v-model="searchForm.createName" style="width: auto"/>
                    </el-form-item>

                    <el-form-item label="事件">
                        <el-select placeholder="事件" clearable size="small" v-model="searchForm.operation">
                            <el-option v-for="item in operationOptions" :key = "item.value" :label = "item.label" :value = "item.value"></el-option>
                        </el-select>
                    </el-form-item>
                    <el-form-item label="审批结果" v-if="this.type.prop === 'approval'">
                        <el-select placeholder="审批结果" clearable size="small" v-model="searchForm.approvalResult">
                            <el-option v-for="item in approvalResultOptions" :key = "item.value" :label = "item.label" :value = "item.value"></el-option>
                        </el-select>
                    </el-form-item>
                </template>

                <template slot-scope="scope" slot="menu">
                    <el-button v-if="$store.state.user.permissions['sys_operationapprovalrecord_approval']" type="primary" size="small" plain @click.stop="handleApproval(scope.row, scope.index)">{{ btnName }}</el-button>
                </template>
            </avue-crud>

**Comment by 1096362029** [comment]
兄弟，多砍看文档啊，
配置searchslot为true即可开启自定义，卡槽的名字为prop+Search，searchMenu为按钮的卡槽

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/crud/crud-search-slot
