### ISSUE TITLE
avue-crud多级联动

### ISSUE THREAD

**Issue by 1096362029** [nmxiaowei/avue#427]
avue-crud标签，**多级联动**（cascaderItem）
点击编辑，再点击取消按钮，表单数据没有删除，就是图中的 dataForm 字段（表单只把二级的label赋值了）
**导致的结果就是，再次去点击新增按钮，会出现数据**
版本 2.7.6
![bug](https://user-images.githubusercontent.com/22360721/105700906-7e851d80-5f44-11eb-981d-6fc90d049c77.gif)

**Comment by nmxiaowei** [comment]
提供下代码

**Comment by 1096362029** [comment]
<template>
    <div class="execution">
        <basic-container>
            <avue-crud ref="crud"
                       v-model="dataForm"
                       :data="tableData"
                       :table-loading="tableLoading"
                       :option="tableOption"
                       @on-load="getList">
            </avue-crud>
        </basic-container>
    </div>
</template>

<script>
    import {fetchList, getObj, addObj, putObj, delObj} from '@/api/sales/distributor'
    import {tableOption} from '@/const/crud/sales/distributor'
    import { parseTime } from '@/util/util'

    export default {
        name: 'distributor',
        data() {
            return {
                dataForm:{},
                searchForm: {},
                tableData: [],
                page: {
                    total: 0, // 总页数
                    currentPage: 1, // 当前页数
                    pageSize: 20 // 每页显示多少条
                },
                tableLoading: false,
                tableOption: {
                    column: [
                        {
                            prop: 'channelCategoryId',
                            span: 12,
                            type: 'select',
                            label: '渠道大类',
                            order:160,
                            hide:true,
                            props: {
                                label: 'name',
                                value: 'id'
                            },
                            cascaderItem: ['channelSubdivideId'],
                            search:true,
                            searchLabelWidth:82,
                            dicUrl: `/sales/channel/selectByParent?parentId=0`,
                            rules: [
                                {
                                    required: true,
                                    message: '请选择',
                                    trigger: 'blur'
                                }
                            ]
                        },
                        {
                            prop: 'channelCategoryName',
                            span: 12,
                            type: 'input',
                            label: '渠道大类',
                            order:50,
                            display:false,
                        },
                        {
                            prop: 'channelSubdivideId',
                            span: 12,
                            type: 'select',
                            label: '渠道细分',
                            order:150,
                            hide:true,
                            props: {
                                label: 'name',
                                value: 'id'
                            },
                            search:true,
                            searchLabelWidth:82,
                            dicUrl: `/sales/channel/selectByParent?parentId={{key}}`,
                            "rules": [
                                {
                                    "required": true,
                                    "message": "请选择",
                                    trigger: 'blur'
                                }
                            ],
                        },
                    ],
                    labelPosition: 'left',
                    labelSuffix: '：',
                    labelWidth: 120,
                    gutter: 0,
                    viewBtn:true,
                    delBtn:false,
                    menuWidth:131,
                    menuBtn: true,
                    submitBtn: true,
                    submitText: '提交',
                    emptyBtn: true,
                    emptyText: '清空',
                    menuPosition: 'center',
                    align: 'center',
                    index: true,
                    border: true,
                    stripe: true,
                    menuAlign: 'center',
                    indexLabel: '序号',
                    searchMenuSpan: 6
                },
            }
        },
        methods: {
            getList(page, params) {
                this.tableLoading = true
                fetchList(Object.assign({
                    current: page.currentPage,
                    size: page.pageSize
                }, params, this.searchForm )).then(response => {
                    this.tableData = response.data.data.records
                    this.page.total = response.data.data.total
                    this.tableLoading = false
                }).catch(() => {
                    this.tableLoading=false
                })
            },
        }
    }
</script>

**Comment by nmxiaowei** [comment]
```
<template>
<div class="execution">
<basic-container>
<avue-crud ref="crud"
v-model="dataForm"
:data="tableData"
:table-loading="tableLoading"
:option="tableOption"
@on-load="getList">
</avue-crud>
</basic-container>
</div>
</template>

<script> import {fetchList, getObj, addObj, putObj, delObj} from '@/api/sales/distributor' import {tableOption} from '@/const/crud/sales/distributor' import { parseTime } from '@/util/util' export default { name: 'distributor', data() { return { dataForm:{}, searchForm: {}, tableData: [], page: { total: 0, currentPage: 1, pageSize: 20 }, tableLoading: false, tableOption: { column: [ { prop: 'channelCategoryId', span: 12, type: 'select', label: '渠道大类', order:160, hide:true, props: { label: 'name', value: 'id' }, cascaderItem: ['channelSubdivideId'], search:true, searchLabelWidth:82, dicUrl: `/sales/channel/selectByParent?parentId=0`, rules: [ { required: true, message: '请选择', trigger: 'blur' } ] }, { prop: 'channelCategoryName', span: 12, type: 'input', label: '渠道大类', order:50, display:false, }, { prop: 'channelSubdivideId', span: 12, type: 'select', label: '渠道细分', order:150, hide:true, props: { label: 'name', value: 'id' }, search:true, searchLabelWidth:82, dicUrl: `/sales/channel/selectByParent?parentId={{key}}`, "rules": [ { "required": true, "message": "请选择", trigger: 'blur' } ], }, ], labelPosition: 'left', labelSuffix: '：', labelWidth: 120, gutter: 0, viewBtn:true, delBtn:false, menuWidth:131, menuBtn: true, submitBtn: true, submitText: '提交', emptyBtn: true, emptyText: '清空', menuPosition: 'center', align: 'center', index: true, border: true, stripe: true, menuAlign: 'center', indexLabel: '序号', searchMenuSpan: 6 }, } }, methods: { getList(page, params) { this.tableLoading = true fetchList(Object.assign({ current: page.currentPage, size: page.pageSize }, params, this.searchForm )).then(response => { this.tableData = response.data.data.records this.page.total = response.data.data.total this.tableLoading = false }).catch(() => { this.tableLoading=false }) }, } } </script>
```

**Comment by nmxiaowei** [comment]
发下格式化的代码，这怎么看

**Comment by 1096362029** [comment]
格式化了
