### ISSUE TITLE
avue-crud 字段名为footer的时候行内编辑和删除按钮列消失

### ISSUE THREAD

**Issue by wxs77577** [nmxiaowei/avue#429]
```js
option: {
   column: [{ prop: "footer", label: 'Footer' }],
},
```
只要column里面字段名prop为`footer`就会这样，没有`footer`就没事

`avue`版本 `2.7.8、2.7.9` 都是这样

**Comment by nmxiaowei** [comment]
![image](https://user-images.githubusercontent.com/35983068/107490535-f8640a80-6bc4-11eb-8556-a609922826db.png)
![image](https://user-images.githubusercontent.com/35983068/107490551-fdc15500-6bc4-11eb-91ce-85c77e8316ca.png)

没有复现
