### ISSUE TITLE
表格子表单,校验无效.

### ISSUE THREAD

**Issue by z363416071** [nmxiaowei/avue#430]
问题:表单组件,存在字表单时候,对子表单的rules设置 无效 .点击提交,返回true成功.官网案例也存在这样的问题.
![image](https://user-images.githubusercontent.com/64683397/106871610-5e581a00-670d-11eb-918a-7880bb65b2b8.png)
avue版本:2.7.9

**Comment by z363416071** [comment]
![image](https://user-images.githubusercontent.com/64683397/106881516-9ca70680-6718-11eb-94b1-aed633dbaa9c.png)
这有问题

**Comment by nmxiaowei** [comment]
更新最新版本即可
