### ISSUE TITLE
avue-data-tabs 显示异常

### ISSUE THREAD

**Issue by gionlee** [nmxiaowei/avue#431]
版本 2.7.0
设置精度 decimals: 2 显示异常
![aec37d4c8935c7e0f63ffddb32afff2](https://user-images.githubusercontent.com/40239468/107116461-c7c75c80-68b6-11eb-882c-2f17ab6e7ebe.png)
![58b62c4b9d36a2cf4094e4ee0df8bd9](https://user-images.githubusercontent.com/40239468/107116464-c8f88980-68b6-11eb-9700-401a8cf0ce23.png)

**Comment by nmxiaowei** [comment]
更新到最新版本
