### ISSUE TITLE
avue分页设置total=0无效

### ISSUE THREAD

**Issue by FJiayang** [nmxiaowei/avue#432]
一、该问题的重现步骤是什么？

1. 配置搜索框清空函数，点击清空后让分页消失
配置代码
```js
searchReset() {
        console.log("清空"+JSON.stringify(this.page))
        this.query = {};
        this.data = [];
        this.page.pageSize= 10;
        this.page.currentPage= 1;
        this.page.total = 0;
      },
```
首次进入页面展示正常，点击搜索后，页面分页正常，点击清空后，表格数据内容清空成功，但分页组件仍然显示上次搜索的分页数据。
控制台日志
```
清空{"pageSize":10,"currentPage":1,"total":1806}
清空{"pageSize":10,"currentPage":1,"total":0}
```

二、你期待的结果是什么？实际看到的又是什么？

希望total为0时分页组件能消失

三、你正在使用的是什么产品，什么版本？在什么操作系统上？

avue 2.7.1

四、请提供详细的错误堆栈信息，这很重要。

无

五、若有更多详细信息，请在下面提供。
当配置改为
```js
searchReset() {
        console.log("清空"+JSON.stringify(this.page))
        this.query = {};
        this.data = [];
        this.page.pageSize= 10;
        this.page.currentPage= 1;
        this.page.total = 1;
      },
```
页面符合预期，点击清空时分页组件显示1

**Comment by nmxiaowei** [comment]
:page.sync=page


需要加sync修饰符





---原始邮件---
发件人: "F_jy"<notifications@github.com&gt;
发送时间: 2021年2月15日(周一) 下午2:42
收件人: "nmxiaowei/avue"<avue@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [nmxiaowei/avue] avue分页设置total=0无效 (#432)




 
一、该问题的重现步骤是什么？
  
配置搜索框清空函数，点击清空后让分页消失
 配置代码 
 searchReset() {         console.log("清空"+JSON.stringify(this.page))         this.query = {};         this.data = [];         this.page.pageSize= 10;         this.page.currentPage= 1;         this.page.total = 0;       },
 
首次进入页面展示正常，点击搜索后，页面分页正常，点击清空后，表格数据内容清空成功，但分页组件仍然显示上次搜索的分页数据。
 控制台日志
 清空{"pageSize":10,"currentPage":1,"total":1806} 清空{"pageSize":10,"currentPage":1,"total":0}  
二、你期待的结果是什么？实际看到的又是什么？
 
希望total为0时分页组件能消失
 
三、你正在使用的是什么产品，什么版本？在什么操作系统上？
 
avue 2.7.1
 
四、请提供详细的错误堆栈信息，这很重要。
 
无
 
五、若有更多详细信息，请在下面提供。
 当配置改为
 searchReset() {         console.log("清空"+JSON.stringify(this.page))         this.query = {};         this.data = [];         this.page.pageSize= 10;         this.page.currentPage= 1;         this.page.total = 1;       },
 
页面符合预期，点击清空时分页组件显示1

**Comment by FJiayang** [comment]
`:page.sync=page`方法有效，已解决
