### ISSUE TITLE
官方文档中示例的问题

### ISSUE THREAD

**Issue by Cnax** [nmxiaowei/avue#434]
### 官方文档中远程搜索多选示例问题

链接：https://avuejs.com/doc/form/form-select-remote

在输入关键字进行远程搜索后，点击下拉列表项中的选项，输入框回显选中的选项文案，同时发送了一个关键字为空的搜索请求。
![image](https://user-images.githubusercontent.com/19279749/108581017-2ab1fc80-7369-11eb-9d9b-dc69347d7e5c.png)

由于官方文档中每次请求的数据都是一样的，没有暴露bug，如果数据不一致，就有回显的数据不是当前选中的选项。

**Comment by nmxiaowei** [comment]
比如删除搜索框内容，应该是空返回数据出现下拉
