### ISSUE TITLE
关于 CRUD 中 datetime 和 dateBtn组件的问题

### ISSUE THREAD

**Issue by lanfen100** [nmxiaowei/avue#437]
错误描述
 问题1：
   CRUD 中 column 项中 type 为 datetime 且 format: "yyyy-MM-dd" ，search:true 时候，日期选择弹框 时间部门显示异常，应该为不显示
 问题2：
   CRUD 开启日期组件  dateBtn:true , 当搜索栏中点击 ”清空“ 清空搜索条件时，dateBtn 内容无法清空
   另外 dateBtn 组件选择 左侧快捷时间区间时候，开始时间的 时分秒应该为 00:00:00 ，目前是 当前的时间点

异常日志
 无
版本号
 V2.7.8

异常截图和代码
   问题1代码及截图：
 column: [
            {
              label: "发生时间",
              prop: "happenTimeRange",
              type:"datetime",
              format: "yyyy-MM-dd",
              valueFormat: "yyyy-MM-dd HH:mm:ss",
              hide: true,
              addDisplay: false,
              editDisplay: false,
              viewDisplay: false,
              span: 12,
              searchRange:true,
              search: true,
              searchSpan:6,
            },
...

![image](https://user-images.githubusercontent.com/12097469/108815213-0c5d3280-75ef-11eb-90a9-018af90d7037.png)

  问题2截图：
![image](https://user-images.githubusercontent.com/12097469/108816526-49c2bf80-75f1-11eb-857e-4a0be8a74a42.png)

**Comment by nmxiaowei** [comment]
你不要时分秒 直接用date组件就好type:date 要不就是配置format:yyyy-MM-dd HH:mm:ss

dateBtn本身就是独立的不和search一起 需要自己点X手动消除
