### ISSUE TITLE
建议表格的 upload 新增上传大小 maxSize 字段和超出大小提示 maxSizeTip 字段

### ISSUE THREAD

**Issue by 1014156094** [nmxiaowei/avue#440]
建议表格的 upload 新增上传大小 maxSize 字段和超出大小提示 maxSizeTip 字段，这是很常见的需求，每个项目都有限制上传大小的需求，导致每个项目都要在 uploadBefore 写判断上传大小的逻辑

![image](https://user-images.githubusercontent.com/16074662/109931203-82eee400-7d03-11eb-80e0-c3cdd2662d3a.png)
![image](https://user-images.githubusercontent.com/16074662/109938954-871eff80-7d0b-11eb-9dc2-84ef2917ea9e.png)

**Comment by nmxiaowei** [comment]
fileSize属性文件大小
触发uploadError函数

**Comment by 1014156094** [comment]
https://www.avuejs.com/doc/form-crud 文档漏了 fileSize 么？

**Comment by nmxiaowei** [comment]
![image](https://user-images.githubusercontent.com/35983068/110052646-e07e4180-7d92-11eb-953f-669ce66cb515.png)
可能缓冲吧

**Comment by 1014156094** [comment]
单位是 MB 还是 KB？
