### ISSUE TITLE
type为tree时怎么获取到过滤后的节点呢

### ISSUE THREAD

**Issue by bigrain220** [nmxiaowei/avue#442]
![image](https://user-images.githubusercontent.com/42227852/110079396-0708a080-7dc4-11eb-9951-7dc4e6d73d1c.png)

我想在搜索的时候，获取到下面的节点集合

![image](https://user-images.githubusercontent.com/42227852/110079614-4b943c00-7dc4-11eb-8a6b-6aeaa0db2302.png)

**Comment by nmxiaowei** [comment]
没有提供改方法
