### ISSUE TITLE
树形选择器懒加载怎么选中默认值？

### ISSUE THREAD

**Issue by Taeyang9861** [nmxiaowei/avue#444]
树形选择器懒加载选择后提交需要编辑，要回显选择的某项怎么做？

![微信图片_20210315174947](https://user-images.githubusercontent.com/37353199/111134763-e48e3880-85b6-11eb-8463-65c470deff5f.png)

**Comment by nmxiaowei** [comment]
不支持，建议采用自定义卡槽
