### ISSUE TITLE
avue-tabs handleSubmit提交时，选项卡属性一直在disabled状态？

### ISSUE THREAD

**Issue by yimaoer** [nmxiaowei/avue#445]
提交之后，一直在disabled中，不能再修改，清空也不能清空disabled状态。

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/form/form-submit

**Comment by yimaoer** [comment]
done 在我用avue-form是可以的，用avue-tabs还是不行，报done is not a function!
![微信截图_20210317155109](https://user-images.githubusercontent.com/21995112/111432950-95025680-86f5-11eb-8642-9c74b7d8e541.png)

**Comment by nmxiaowei** [comment]
更新到最新版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 下午3:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [nmxiaowei/avue] avue-tabs handleSubmit提交时，选项卡属性一直在disabled状态？ (#445)




 
done 在我用avue-form是可以的，用avue-tabs还是不行，报done is not a function!
