### ISSUE TITLE
表单弹窗有一项树形选择，树形选择数据太大导致弹窗卡顿

### ISSUE THREAD

**Issue by Taeyang9861** [nmxiaowei/avue#446]
树形选择项绑定数据网为全国所有省市，导致调起弹窗长达两秒，并且输入其他input内容卡顿
![微信截图_20210317104612](https://user-images.githubusercontent.com/37353199/111408453-48784480-8710-11eb-890f-ce6c12b78260.png)

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/form/form-cascader
可以采用懒加载
