### ISSUE TITLE
crud高度计算有问题

### ISSUE THREAD

**Issue by shaokuuipo** [nmxiaowei/avue#447]
version：2.8.1
把crud分别封装到两个组件中。主页面import这两个组件，并用tab分别包裹，默认显示的tab中的crud高度没有问题，切换到第二个tab中，第二个crud的高度计算错误。

**Comment by nmxiaowei** [comment]
发option配置

**Comment by shaokuuipo** [comment]
主页面
`<template>
  <el-tabs v-model="activeName" type="card" @tab-click="handleClick">
    <el-tab-pane label="待派单" name="dpd"><dpd ref="dpd" v-if="activeName == 'dpd'"></dpd></el-tab-pane>
    <el-tab-pane label="已派单" name="ypd"><ypd ref="ypd" v-if="activeName == 'ypd'"></ypd></el-tab-pane>
  </el-tabs>
</template>

<script>
import dpd from "./dpd.vue";
import ypd from './ypd.vue';

export default {
  components: { dpd,ypd },
  data() {
    return {
      activeName: "dpd",
    };
  },
  computed: {},
  methods: {
    handleClick(tab) {
      this.activeName = tab.name;
    },
  },
};
</script>
<style>
</style>
`

**Comment by shaokuuipo** [comment]
两个组件的配置是一样的。
option: {
        height: "auto",
        calcHeight: 125,
        tip: false,
        searchShow: true,
        searchMenuSpan: 6,
        border: true,
        index: true,
        selection: false,
        //dialogType: 'drawer',
        labelWidth: 120,
        searchLabelWidth: 100,
        menuWidth: 300,
        dialogClickModal: false,
        editTitle: "转派",
        // editBtnText: '转派',
        updateBtnText: "转派",
        addBtn: false,
        editBtn: false,
        delBtn: false,
        viewBtn: false,
        // updateBtn: false,
        // cancelBtn: false,
        size: "mini",
        column: []
}

**Comment by nmxiaowei** [comment]
加载的时候给crud组件加一个v-if 
切换过去时候先设置为false 再设置成true 让它重绘

**Comment by shaokuuipo** [comment]
现在就是这样解决这个问题的。
