### ISSUE TITLE
表单 type: "upload" 点击图片不能预览，希望优化~

### ISSUE THREAD

**Issue by 1014156094** [nmxiaowei/avue#451]
![image](https://user-images.githubusercontent.com/16074662/112959212-c78c6480-9175-11eb-9ee2-c5e21702c2bd.png)
![image](https://user-images.githubusercontent.com/16074662/112959115-adeb1d00-9175-11eb-95bc-fd5220688a44.png)

**Comment by nmxiaowei** [comment]
el底层就是这么设定的，建议采用自定义卡槽

**Comment by 1014156094** [comment]
表单加个 click 触发旁边的标题可以么？
