### ISSUE TITLE
表格的操作国际化怎么添加，引入了 element-ui 的本地语言包，但是还是不管用

### ISSUE THREAD

**Issue by xyy547491937** [nmxiaowei/avue#453]
![image](https://user-images.githubusercontent.com/25171918/113095235-adaa5a80-9225-11eb-8aeb-287122b641e9.png)
查看配置文件没有配置操作这个栏位 的，引入本地语言包也没管用，求帮忙

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/i18n

**Comment by yyman001** [comment]
> https://avuejs.com/doc/i18n

404
