### ISSUE TITLE
upload组件上传mp3音频格式后，预览时显示为图片bug

### ISSUE THREAD

**Issue by flymorn** [nmxiaowei/avue#457]
upload组件上传mp3格式的音频后，预览时出错了：
{
            label: "音频素材",
            prop: "audios",
            type: "upload",
            accept: ["audio/mpeg"],
}
文件可以上传成功到阿里云oss了。

错误截图：
![1](https://user-images.githubusercontent.com/17798085/114006395-fc459d80-9892-11eb-9980-6369de66b4d4.jpg)
![2](https://user-images.githubusercontent.com/17798085/114006405-fd76ca80-9892-11eb-9c53-cb740a389923.jpg)
 
而如果上传mp4视频格式时，则可以正常预览。

请修复，谢谢。

**Comment by nmxiaowei** [comment]
![image](https://user-images.githubusercontent.com/35983068/114366201-cadc1300-9bad-11eb-9df4-29d3eaa4bf4c.png)
采用列表形式，结合:upload-preview="uploadPreview" 使用
https://avuejs.com/doc/form/form-upload

**Comment by lcy7** [comment]
请问这个问题有解决吗
