### ISSUE TITLE
cascader 在表格里面无法设置默认值

### ISSUE THREAD

**Issue by carter911** [nmxiaowei/avue#458]
单纯使用表单可以设置默认值 但是在表格里面使用表单的cascader默认值一直不生效
`let dicData =[
                {
                    label:1,
                    value:1,
                    children:[
                        { label:11,
                            value:11,
                        },
                        { label:12,
                            value:12,
                        }
                    ],
                }
            ]

 form:{
                    test:[1,11],
                },

{
                            label:'ACCOUNT',
                            prop:'test',
                            type:'cascader',
                            width:120,
                            span:24,
                            overHidden:true,
                            filterable:true,
                            // parent:false,
                            dicData:dicData,
                            rules: [{
                                required: true,
                                message: "ACCOUNT is must",
                                trigger: "blur"
                            }],
                        },`

**Comment by nmxiaowei** [comment]
配置value:'xxxx'

**Comment by carter911** [comment]
我是一个curd组件 那每个都要动态设置value值？
