### ISSUE TITLE
表单 type: "upload" 点击图片不能预览，希望优化~

### ISSUE THREAD

**Issue by 1014156094** [nmxiaowei/avue#460]
![image](https://user-images.githubusercontent.com/16074662/112959212-c78c6480-9175-11eb-9ee2-c5e21702c2bd.png)
![image](https://user-images.githubusercontent.com/16074662/112959115-adeb1d00-9175-11eb-95bc-fd5220688a44.png)

现状：点击图片不能出现预览，点击图片标题能出现预览
预期：点击图片出现预览
建议：给图片加个 click 触发旁边的标题，就可以实现点击图片出现预览了。
avue 版本：2.7.8

**Comment by nmxiaowei** [comment]
el底层就是这么设定，无法更改

**Comment by 1014156094** [comment]
> el底层就是这么设定，无法更改

有办法的吧，按照我建议里面的思路
