### ISSUE TITLE
关于avue  avue-crud  组件展开收起翻译的问题

### ISSUE THREAD

**Issue by xyy547491937** [nmxiaowei/avue#464]
引入avue 的组件翻译，但是展开收起 还是没有翻译， 是不是没有做处理啊

![9b416bf64982f1ef785e869f75366b5](https://user-images.githubusercontent.com/25171918/116644774-d9e10480-a9a6-11eb-90bc-8008a7f174b6.png)

**Comment by nmxiaowei** [comment]
更新到最新版本即可
