### ISSUE TITLE
upload的控件需要一个完整的异常处理机制

### ISSUE THREAD

**Issue by gaoag2006** [nmxiaowei/avue#467]
上传一旦因为预料之外的原因失败，整个控件就会卡死在loading状态，想继续使用必须刷新页面

**Comment by nmxiaowei** [comment]
在uploadAfter函数有一个loading函数，调用一下即可关闭等待框，详情看官网例子



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月10日(周一) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [nmxiaowei/avue] upload的控件需要一个完整的异常处理机制 (#467)




 
上传一旦因为预料之外的原因失败，整个控件就会卡死在loading状态，想继续使用必须刷新页面

**Comment by nmxiaowei** [comment]
https://avuejs.com/doc/form/form-upload

**Comment by gaoag2006** [comment]
> https://avuejs.com/doc/form/form-upload

收到 。另，例子中loading仅是作为参数出现，并没有相关的应用

**Comment by nmxiaowei** [comment]
loading()
即可关闭等待框
