### ISSUE TITLE
upload无法正确识别从服务器端取得的视频文件

### ISSUE THREAD

**Issue by gaoag2006** [nmxiaowei/avue#472]
file对象的信息如下：
{
  "uid": "0",
  "status": "done",
  "isImage": true,
  "name": "yyy.mp4",
  "url": "http://xxx/yyy.mp4"
}
isImage属性的值应该为true吗？
页面上无法预览该视频，原因是使用了img标签，手动修改为video标签后，可以正常的预览了

**Comment by gaoag2006** [comment]
按照例子做过测试，目前只有listType:picture-img能够正常的显示  picture-card不能正常显示

**Comment by nmxiaowei** [comment]
只有picture-img支持视频

**Comment by nmxiaowei** [comment]
其它的可以利用upload卡槽自定义

**Comment by gaoag2006** [comment]
提个建议，picture-img这种模式多应用于头像之类的，其他的应用场景应该没有picture-card模式广，picture-card模式支持视频的意义比较大
