### ISSUE TITLE
upload组件删除初始化取得的上传图片后再上传新图片，已经删除的图片再次出现

### ISSUE THREAD

**Issue by gaoag2006** [nmxiaowei/avue#473]
步骤：
1.upload组件（picture-card模式）先从服务器端取得之前已经上传的图片并显示
2.从这些图片中删除一张图片
3.上传新的图片
现象：
之前删除的图片又出现了，如果退出该画面再次进入，之前删除的图片不会显示

**Comment by gaoag2006** [comment]
column           
 {
    label: "图片上传",
    labelWidth: 120,
    prop: "aaaa",
    type: "upload",
    accept:"image/gif,.jpg,.jpeg,.png,.GIF,.JPG,JPEG,.PNG",
    span: 24,
    hide: true,
    minWidth: 250,
    multiple: true,
    listType: "picture-card",
    action: "bbbb",
    propsHttp: {
      home: "cccc",
      url: "key"
    }
  },
form的值为
[{label:xxxx1, value:yyyy1}, {label:xxxx2, value:yyyy2}, {label:xxxx3, value:yyyy3}]

**Comment by nmxiaowei** [comment]
更新到最新版本
