### ISSUE TITLE
xss 问题

### ISSUE THREAD

**Issue by tuoxiaozhong** [nmxiaowei/avue#479]
数据中如果出现html标签，会以v-html的方式直接渲染到页面，xss风险极高。建议添加html 类型的属性，并添加xss 白名单配置。

由于这个问题我被安全diss了，自己fork了一份先解决了，希望早点回归主链，┭┮﹏┭┮

**Comment by nmxiaowei** [comment]
目前2.0不做调整，预计3.0中去优化
