### ISSUE TITLE
vue2.6.13中操作栏不显示按钮

### ISSUE THREAD

**Issue by wuhan169** [nmxiaowei/avue#480]
vue 2.6.13
element 2.15.2
avue 2.8.12

crud组件中操作栏不显示按钮
![image](https://user-images.githubusercontent.com/13692093/120581129-da186800-c45c-11eb-867f-9eeb64ac1aaa.png)

将vue还原为2.6.12后可以显示
![image](https://user-images.githubusercontent.com/13692093/120581173-eb617480-c45c-11eb-8aff-ef1c5a21d18e.png)

**Comment by nmxiaowei** [comment]
https://gitee.com/log4j/pig/issues/I3U3HQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nmxiaowei/avue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 中午11:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[nmxiaowei/avue] vue2.6.13中操作栏不显示按钮 (#480)





 
vue 2.6.13
 element 2.15.2
 avue 2.8.12
 
crud组件中操作栏不显示按钮
 
 
将vue还原为2.6.12后可以显示

**Comment by nmxiaowei** [comment]
https://github.com/vuejs/vue/issues/12102
