### ISSUE TITLE
form数据绑定问题

### ISSUE THREAD

**Issue by anna647** [nmxiaowei/avue#481]
大神请教下，新增和编辑用的el-dialog对话框，新增会把v-model赋成空对象

![image](https://user-images.githubusercontent.com/12045697/120786781-3664b000-c561-11eb-8d8f-c000d7980e62.png)

![image](https://user-images.githubusercontent.com/12045697/120788007-8ee87d00-c562-11eb-8f51-e381505c1afd.png)

![image](https://user-images.githubusercontent.com/12045697/120788045-9871e500-c562-11eb-820f-b407afebc835.png)

但是详情的form里会有冗余数据，打开新增时，看到form变成了{}，但是页面的数据一变化，上次赋值的冗余数据全出来了form值发生了变化，这是什么原因呀？

**Comment by anna647** [comment]
版本2.7.6

**Comment by nmxiaowei** [comment]
https://blog.csdn.net/lihefei_coder/article/details/88185234
