### ISSUE TITLE
avue-crud新增时输入特殊字符

### ISSUE THREAD

**Issue by Jenny-start** [nmxiaowei/avue#484]
avue-crud新增时输入特殊字符，对应的列为空。例如输入null,undefined，查看时却显示

![image](https://user-images.githubusercontent.com/28924992/121473597-7f02ea00-c9f5-11eb-9819-74b8a1352940.png)
![image](https://user-images.githubusercontent.com/28924992/121473726-aa85d480-c9f5-11eb-8025-09341f3f26fe.png)

**Comment by Jenny-start** [comment]
![image](https://user-images.githubusercontent.com/28924992/121474746-161c7180-c9f7-11eb-8c08-6e0fee1f527a.png)
代码部分

**Comment by nmxiaowei** [comment]
提交的时候可以后台处理 
处理成“”
