### ISSUE TITLE
showColumn

### ISSUE THREAD

**Issue by Taeyang9861** [nmxiaowei/avue#489]
showColumn属性失效
官方文档显示也是不正确的
![微信截图_20210621105524](https://user-images.githubusercontent.com/37353199/122701243-627d7200-d27f-11eb-9261-5e99ce84437e.png)
![微信截图_20210621105536](https://user-images.githubusercontent.com/37353199/122701248-6610f900-d27f-11eb-845c-a7a7869b6765.png)

**Comment by nmxiaowei** [comment]
showColumn属性做了变动，他不会再显隐里面出现，列表不出现需要配合hide:true
