### ISSUE TITLE
某些情况下，column type:tree，选中后没有对应名称回显

### ISSUE THREAD

**Issue by 948911908** [nmxiaowei/avue#495]
![image](https://user-images.githubusercontent.com/19320137/126117436-a2c6ee82-f9c5-420c-8912-7f0ea9b0f957.png)
version：2.8.15
当type:tree 的column，设置了lazy:true之后就没有对应名称回显，反之则有

**Comment by nmxiaowei** [comment]
目前懒加载不支持
