### ISSUE TITLE
2.8.14图片上传组件问题反馈.求解答.

### ISSUE THREAD

**Issue by everdt-MaShuai** [nmxiaowei/avue#497]
版本号 2.8.14

图片上传组件.我在改造成假上传回显的过程中.
发现你对返回的url用逗号进行了split操作.
导致base64图片被切分无法显示.
这个地方正常上传图片但是url地址中带有逗号的图片也有无法显示的错误.

**Comment by nmxiaowei** [comment]
返回的数据为数组即可[x1,x2,x3]

**Comment by everdt-MaShuai** [comment]
我的数据本身就是一个组件多图,数据结构就是[x1,x2,x3]
但组件依旧进行了二次split.
这个组件对每个x都进行了","的split操作.
url里面只要有逗号组件直接就无法使用.
