### ISSUE TITLE
2.8.17版本，列名称Form(nameForm) 使用scope时，没有row属性了

### ISSUE THREAD

**Issue by xiaoweifeilang** [nmxiaowei/avue#500]
"@smallwei/avue": "^2.8.17"，列名称Form(nameForm) 使用scope时，没有row属性了，多了个value属性？

{ "value": "", "column": { "label": "", "prop": "nameCn", "formslot": true, "rules": [ { "required": true, "message": "", "trigger": "blur" } ], "width": 140, "index": "", "boxType": "edit", "dicFlag": false }, "size": "mini", "disabled": false, "type": "edit" }

**Comment by nmxiaowei** [comment]
表单没有row的方法
直接用v-model即可
https://avuejs.com/crud/crud-formslot.html#%E6%99%AE%E9%80%9A%E7%94%A8%E6%B3%95
