### ISSUE TITLE
v2.8.25版本，子表单里拿不到当前行index，导致无法与当前行其他表单联动

### ISSUE THREAD

**Issue by Mrblackant** [nmxiaowei/avue#521]
如图所示，我想在子表单里的输入框，失焦blur后拿到当前行的"**表格**"里的值然后做计算，但是blur里只能拿到({value,column})，

没办法判断当前行的index，导致无法联动，但是**change**事件能拿到index，只有blur、focus、click里取不到，这跟官网文档里列的参数不一样啊，如代码所示:

` column: [{
              label: '输入框',
              prop: "input",
              blur: ({ value, column, row, index }) => {
                console.log('')
                console.log('blur------')
                console.log(value)
                console.log(column)
                console.log(row)
                console.log(index)
              },
              change: ({ value, column, row, index }) => {
                console.log('')
                console.log('---change')
                console.log(value)
                console.log(column)
                console.log(row)
                console.log(index)
              },
            }]`
**请问怎么在子表单里，在表单元素blur、focus、click等操作后拿到当前行的index**
![image](https://user-images.githubusercontent.com/23350450/148177970-2f6e8a52-381c-4dc5-8853-18801904f3ce.png)

https://v3.avuejs.com/views/doc.html

**Comment by nmxiaowei** [comment]
https://avuejs.com/crud/crud-children.html
https://avuejs.com/crud/crud-cell.html
参考这2个
