### ISSUE TITLE
form表单中column中允许引用component组件，二次开发嘛？

### ISSUE THREAD

**Issue by yumenglong** [nmxiaowei/avue#526]
想开发一个组件在form中引用，但是怎么让组件在提交表单的时候，值赋值到prop这个值上？类似于编辑器这种。
![image](https://user-images.githubusercontent.com/17467365/151331099-044c04e6-10f3-4dbb-b899-23488c409a0d.png)

自己开发的组件入下图所示：
![image](https://user-images.githubusercontent.com/17467365/151331164-58f58d7c-e416-4ee0-a063-65090e2d163a.png)
![image](https://user-images.githubusercontent.com/17467365/151331189-7963af65-25e2-483b-8edc-b83be3d9a0c6.png)

在form表单提交的时候：
![image](https://user-images.githubusercontent.com/17467365/151331232-7a4b21b5-e4ef-4e8b-b19e-e2b853660674.png)

**Comment by nmxiaowei** [comment]
利用v-model
