### ISSUE TITLE
form 表单select组件

### ISSUE THREAD

**Issue by QinHongYang** [nmxiaowei/avue#529]
type:'select'，在使用dicUrl请求数据渲染，我该如何追加一条数据，例如：数据请求出来只有A，B，C三个选项，现在要新增一个全部的选项，我希望能通过某个属性去动态添加到选项的前面或者后面

**Comment by nmxiaowei** [comment]
dicFormatter
https://avuejs.com/form/form-dic.html
```
dicFormatter:(res)=>{
          res.unshift({name:'追加数据',code:-1})
          return res
    },
```
