### ISSUE TITLE
表格select渲染问题v2.8.26

### ISSUE THREAD

**Issue by QinHongYang** [nmxiaowei/avue#534]
![image](https://user-images.githubusercontent.com/53382264/155483973-4a92a255-244a-4f45-93ed-75848cf9d79d.png)
我通过dicUrl查询的key是string类型，而在表格onload->getList方法中查询出来toolType的类型是number类型，在v2.5.0中我使用formatter方法将值转为字符类型，就能渲染出对应的 select option，升级后就不行了，显示的还是key
![image](https://user-images.githubusercontent.com/53382264/155484886-ffd571cd-c497-4919-b98c-eff8784f78ed.png)

**Comment by nmxiaowei** [comment]
你格式化了 用的value 肯定是没翻译的

**Comment by nmxiaowei** [comment]
![image](https://user-images.githubusercontent.com/35983068/155685998-82f6d0dd-64dd-47d6-8996-c1f72c51338f.png)
取label

**Comment by QinHongYang** [comment]
我通过dicUrl查询的key是“**string类型**”，而在表格onload->getList方法中查询出来toolType的类型是“**number类型**”，导致翻译不了，我直接去label也是没翻译的，因为select option 的value是string类型，而我查出来的数据值number类型，1不等于'1'，所以我想在formatter中返回字符类型的值，
在这个版本中就不生效了，在v2.5.0中formatter->return 后还会去翻译，这个版本好像以formatter 返回的值为最终的值，不会去执行翻译，
