### ISSUE TITLE
表单级联选择器回显问题

### ISSUE THREAD

**Issue by QinHongYang** [nmxiaowei/avue#544]
![image](https://user-images.githubusercontent.com/53382264/158722710-8f1b1575-2810-440c-b593-3cd1e9a1239a.png)
![image](https://user-images.githubusercontent.com/53382264/158722767-7ea60266-f44b-4501-a2f2-5fce00aa18c0.png)
![image](https://user-images.githubusercontent.com/53382264/158722799-df3cbd92-543f-461d-942c-ffc55273821c.png)
设置初始值并不会回显，我该如何操作？

**Comment by nmxiaowei** [comment]
版本号

**Comment by QinHongYang** [comment]
> 版本号

v2.8.26

**Comment by nmxiaowei** [comment]
https://avuejs.com/form/form-cascader.html#%E6%90%9C%E7%B4%A2
例子试了下没问题
