### ISSUE TITLE
avue-crud中设置下拉框select回显的值错误

### ISSUE THREAD

**Issue by CUE-123** [nmxiaowei/avue#548]
![捕获1](https://user-images.githubusercontent.com/33414201/160738173-770e08a1-9d26-4693-84f7-c7f85b74b703.PNG)
![捕获2](https://user-images.githubusercontent.com/33414201/160738176-a1912a1d-5146-448b-b2c7-80c509058b5e.PNG)
![捕获3](https://user-images.githubusercontent.com/33414201/160738177-0884a6e0-dff7-48dc-ad04-d84c0ffb9ddb.PNG)
![捕获4](https://user-images.githubusercontent.com/33414201/160738179-65693798-d1b1-4401-9e02-7958d54dfd45.PNG)

**Comment by nmxiaowei** [comment]
字典的数据要和值的数据一致，都是string/number。要不配置dataType:'number' 统一类型
