### ISSUE TITLE
如何把获取的后端数据放到添加页面中的下拉框现实出来

### ISSUE THREAD

**Issue by CUE-123** [nmxiaowei/avue#553]
![捕获1](https://user-images.githubusercontent.com/33414201/162890851-04fb339c-0200-4fff-98cc-0a920ff86c50.PNG)
![捕获2](https://user-images.githubusercontent.com/33414201/162890855-344db2c7-a3cd-40a7-8f11-2c2407f237d7.PNG)
![捕获3](https://user-images.githubusercontent.com/33414201/162890857-73fe8779-3da3-4c48-a187-0152e1e512ec.PNG)
![捕获4](https://user-images.githubusercontent.com/33414201/162890861-996cef3c-a4bd-4e2c-9ea5-493d94926b2b.PNG)

**Comment by nmxiaowei** [comment]
https://avuejs.com/crud/crud-dic.html

**Comment by nmxiaowei** [comment]
https://avuejs.com/form/form-dic.html

**Comment by CUE-123** [comment]
还有没有其他的解决办法
