### ISSUE TITLE
用户登录成功，将账号密码保存在浏览器，打开用户管理新增界面用户名和密码会自动出现，如何解决在浏览器保存账号密码情况下不让用户名和密码出现

### ISSUE THREAD

**Issue by CUE-123** [nmxiaowei/avue#557]
![捕获](https://user-images.githubusercontent.com/33414201/167102561-57e73cfe-05f0-46c7-b33b-1a55d8db315a.PNG)

**Comment by nmxiaowei** [comment]
https://blog.csdn.net/qq_44552416/article/details/122470948
