### ISSUE TITLE
如何获取的后端数据回填的单选框音量框中

### ISSUE THREAD

**Issue by CUE-123** [nmxiaowei/avue#558]
![捕获1](https://user-images.githubusercontent.com/33414201/167531703-b399947c-be78-4ed3-b9c9-cf92de3f13aa.PNG)
![捕获2](https://user-images.githubusercontent.com/33414201/167531706-52da70f3-66c6-49ba-88a1-f875c831d21b.PNG)
![捕获3](https://user-images.githubusercontent.com/33414201/167531709-5e46b921-1381-4a02-9881-7bfdc6024244.PNG)
![捕获4](https://user-images.githubusercontent.com/33414201/167531710-83914d10-6917-4557-87b6-919b179da504.PNG)
![捕获5](https://user-images.githubusercontent.com/33414201/167531712-9942cec2-db60-4b01-8885-429f1f379937.PNG)
![捕获6](https://user-images.githubusercontent.com/33414201/167531713-69fbf286-f070-45b2-83df-33c9a22dad99.PNG)

**Comment by nmxiaowei** [comment]
https://avuejs.com/form/form-dic.html

**Comment by nmxiaowei** [comment]
完后用v-model赋值
