### ISSUE TITLE
从v2.6.18升级到v2.9.7后预期的表单【允许空字符串】失效了

### ISSUE THREAD

**Issue by ConnorGodBike** [nmxiaowei/avue#561]
【row-update方法里返回表单数据去掉空数据】请问有没有开放新的参数以支持【允许空字符串】
![image](https://user-images.githubusercontent.com/30334616/168093843-0aef5365-c494-4537-ba15-a28fac5f36c3.png)

**Comment by nmxiaowei** [comment]
利用v-model绑定的对象。里面有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月12日(周四) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [nmxiaowei/avue] 从v2.6.18升级到2.9.7后预期的表单【允许空字符串】失效了 (Issue #561)




 
【row-update方法里返回表单数据去掉空数据】请问有没有开放新的参数以支持【允许空字符串】

**Comment by ConnorGodBike** [comment]
通过给avue-crud添加v-model已解决
