### ISSUE TITLE
如何实现每次加载弹窗加载onload

### ISSUE THREAD

**Issue by thf76** [nmxiaowei/avue#574]
![32a5e24398ad3249f2879de83ff8be9](https://user-images.githubusercontent.com/14136968/184791659-0b310f91-8cdf-4312-ac74-b7242f1e3c7c.png)
![ba51107295ee6d249e94833f5cce082](https://user-images.githubusercontent.com/14136968/184791759-7fdbff43-2b74-415f-acb4-d1f6b20ab67a.png)

弹窗onload只加载一次，能不能点弹窗每次onload都加载，因为每次点弹窗时可能传的条件不一样。

**Comment by nmxiaowei** [comment]
2.9.14+版本更新

**Comment by nmxiaowei** [comment]
每次点击出来弹窗，都会调用onLoad方法的
2.9.13测试
