### ISSUE TITLE
avue不能使用vue devtool

### ISSUE THREAD

**Issue by fingertips-Lyb** [nmxiaowei/avue#575]
错误描述
avue项目vue devtools图标能点亮，但无法进行调试

异常日志

版本号
2.9.5

异常截图和代码
![image](https://user-images.githubusercontent.com/60499266/184793815-b4f94daa-8a21-4787-9e86-ab8ba520ed69.png)

采用网上的方法不起作用：
```js
const isProd = process.env.NODE_ENV === "production";
if (!isProd) {
  Vue.config.devtools = true;
}
```

**Comment by nmxiaowei** [comment]
import Avue from '@smallwei/avue/lib/avue.js'
