### ISSUE TITLE
CURD弹窗表单中select的option自定义渲染问题

### ISSUE THREAD

**Issue by DamonSnow** [nmxiaowei/avue#580]
CURD弹窗表单中若使用select，如何将select的option自定义渲染。例如下图：
![image](https://user-images.githubusercontent.com/18485833/189081135-eaee242d-0788-4e7e-b2b8-cce617851a3f.png)

**Comment by nmxiaowei** [comment]
https://avuejs.com/form/form-select/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF
