### ISSUE TITLE
表格树 修改了parentId 后 done(row) 无效，该如何刷新节点

### ISSUE THREAD

**Issue by y-90** [nmxiaowei/avue#582]
表格树 修改了parentId 后 done(row) 无效，该如何刷新节点

**Comment by nmxiaowei** [comment]
https://avuejs.com/crud/crud-tree/
参考例子

**Comment by y-90** [comment]
已经参考，无法刷新 （将A节点下的a节点，变更到B节点下去）

**Comment by nmxiaowei** [comment]
这个不支持，只能同级下 2.10.2版本支持下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月27日(周二) 下午4:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [nmxiaowei/avue] 表格树 修改了parentId 后 done(row) 无效，该如何刷新节点 (Issue #582)
