### ISSUE TITLE
如何把校验产生的红字去除

### ISSUE THREAD

**Issue by chiewm** [nmxiaowei/avue#584]
错误描述
如图，有一个切换是否校验的按钮，首次提交因校验产生了红字，切换到【否】时，此时校验全部移除，但是红字仍然存在，如何把这个红字移除？

版本号
2.10.4

异常截图和代码
![image](https://user-images.githubusercontent.com/20594982/200108498-a680fef1-913f-42f9-b186-41b7ee6356ff.png)

**Comment by flysnoopycx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!

**Comment by nmxiaowei** [comment]
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/35983068/200208823-780b651e-7837-4d81-b8ee-3fdadab2673b.png">

this.$refs.form.clearValidate
