### ISSUE TITLE
自定义编辑是不是改版了

### ISSUE THREAD

**Issue by Triumph297** [nmxiaowei/avue#595]
以前点完编辑是这个样子的
![image](https://user-images.githubusercontent.com/79828369/208567402-b48ea186-e6a0-4e53-9e0d-598a284fbb47.png)
但现在官网点完编辑保存后这样的
![image](https://user-images.githubusercontent.com/79828369/208567721-567163ec-a659-4f50-96d5-75f73782f03e.png)

**Comment by nmxiaowei** [comment]
https://avuejs.com/crud/crud-cell/#
