### ISSUE TITLE
锚点问题

### ISSUE THREAD

**Issue by xixiaochou** [nmxiaowei/avue#597]
给页面设置锚点，avue-tag不见了，就是那个标签页
![image](https://user-images.githubusercontent.com/89841527/210507079-da00282f-b4d2-4713-8669-b6fbc755c942.png)
![image](https://user-images.githubusercontent.com/89841527/210507126-ac54095e-6af2-4e37-92ad-9a0c29403ecc.png)

**Comment by nmxiaowei** [comment]
不支持
