### ISSUE TITLE
DataCardtext 数据展示 无法显示图标

### ISSUE THREAD

**Issue by 1340145680** [nmxiaowei/avue#601]
DataCardtext 数据展示   的图标都无法显示了，旧版就有新版都没了
![image](https://user-images.githubusercontent.com/91125707/221395902-cf218370-c6d4-4484-8c7d-5d7af4cd18a2.png)
![image](https://user-images.githubusercontent.com/91125707/221395909-0c9fa4c5-f3db-4ebe-88f2-ca3e7a90ca74.png)
![image](https://user-images.githubusercontent.com/91125707/221395917-208c30f9-733b-48b2-ab3e-20451cbd5f36.png)
![image](https://user-images.githubusercontent.com/91125707/221395919-7fab8092-9d9d-4a8f-83ca-95eb2becd3e7.png)

**Comment by nmxiaowei** [comment]
版本号
