### ISSUE TITLE
更新异步数据后，分页总数未更新

### ISSUE THREAD

**Issue by WinnieWei0** [nmxiaowei/avue#604]
使用AVue CRUD组件的分页组件，自己添加的按钮切换数据，数据异步请求成功后更新总条数，总条数和分页数更新失败
效果如图：任务待办没有数据，分页仍为开发待办数据
![image](https://user-images.githubusercontent.com/29709910/224657122-e98c3df8-d556-4678-ac00-e53321a15713.png)

版本号：
    "vue": "^2.6.10"
    "element-ui": "^2.15.6"
    avue: 2.9.12

**Comment by nmxiaowei** [comment]
:page.sync=page 具体看官网文档用法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月14日(周二) 上午10:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [nmxiaowei/avue] 更新异步数据后，分页总数未更新 (Issue #604)




 
使用AVue CRUD组件的分页组件，自己添加的按钮切换数据，数据异步请求成功后更新总条数，总条数和分页数更新失败
 效果如图：任务待办没有数据，分页仍为开发待办数据
 
 
版本号：
 "vue": "^2.6.10"
 "element-ui": "^2.15.6"
 avue: 2.9.12

**Comment by nmxiaowei** [comment]
[a

a](https://avuejs.com/crud/crud-page/)
