### ISSUE TITLE
avue-crud新增/编辑数据时不能够拿到远端数据

### ISSUE THREAD

**Issue by mr-xu1996** [nmxiaowei/avue#606]
1. 错误日志
`<avue-crud
      :data="data"
      :option="option"
      :page.sync="page"
      :search.sync="search"
      @row-del="rowDel"
      @row-save="handleRowSave"
      @on-load="onLoad"
      @row-update="handleRowUpdate"></avue-crud>`
option.column的值为
```
[
    {
        "type": "input",
        "label": "性别",
        "span": 24,
        "display": true,
        "prop": "a167774311222923573"
    },
    {
        "type": "input",
        "label": "身份证",
        "span": 24,
        "display": true,
        "prop": "a167774314342044044"
    },
    {
        "type": "input",
        "label": "年龄",
        "span": 24,
        "display": true,
        "prop": "a167774315022073818"
    },
    {
        "type": "input",
        "label": "学校",
        "span": 24,
        "display": true,
        "prop": "a167841173568526915"
    },
    {
        "type": "checkbox",
        "label": "多选框组",
        "span": 24,
        "display": true,
        "props": {
            "label": "label",
            "value": "value"
        },
        "prop": "a167990577526759149",
        "dicMethod": "get",
        "dicUrl": "xxxx"
    }
]
```

2.异常截图
页面创建时或者点击按钮之后不会发起"dicUrl": "xxxx"数据请求
![image](https://user-images.githubusercontent.com/68182327/227898605-8ab232a6-325f-4744-8723-356a1bb97835.png)

3.版本号  "@smallwei/avue": "^2.10.7",   浏览器版本号 Google Chrome：版本 100.0.4896.88（正式版本） （64 位）

4.希望能正常获取远端数据

**Comment by nmxiaowei** [comment]
https://avuejs.com/crud/crud-form/#%E6%89%93%E5%BC%80%E8%A1%A8%E5%8D%95%E5%89%8D

打开表单前获取

**Comment by nmxiaowei** [comment]
https://avuejs.com/crud/crud-ajax/#%E9%85%8D%E7%BD%AE%E9%A1%B9%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8A%A0%E8%BD%BD

初始化一下

**Comment by nmxiaowei** [comment]
https://avuejs.com/form/form-dic/#%E4%BF%AE%E6%94%B9%E6%95%B0%E6%8D%AE
修改数据字典

**Comment by mr-xu1996** [comment]
thanks

**Comment by Eileen-v** [comment]
> 
你好，我也遇到了同样的问题，但是尝试在beforeOpen中更新没有成功，请问你是怎么解决的呀

**Comment by Eileen-v** [comment]
> https://avuejs.com/crud/crud-form/#%E6%89%93%E5%BC%80%E8%A1%A8%E5%8D%95%E5%89%8D
> 
> 打开表单前获取

你好，我也遇到了同样的问题，但是尝试在beforeOpen中更新没有成功，请问你是怎么解决的呀
