### ISSUE TITLE
CRUD组件，列显隐保存后，Select就用不了

### ISSUE THREAD

**Issue by tatdamail** [nmxiaowei/avue#607]
https://avuejs.com/crud/crud-column/#%E6%94%B9%E5%8F%98%E7%BB%93%E6%9E%84%E9%85%8D%E7%BD%AE
如果表单里有select组件，只要保存了列配置，就无法使用select组件。
select用了服务器数据。配置了dicUrl.

**Comment by nmxiaowei** [comment]
https://avuejs.com/form/form-dic/#%E4%BF%AE%E6%94%B9%E6%95%B0%E6%8D%AE

**Comment by nmxiaowei** [comment]
https://avuejs.com/crud/crud-ajax/#%E9%85%8D%E7%BD%AE%E9%A1%B9%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8A%A0%E8%BD%BD
