### ISSUE TITLE
form设置行内样式不美观

### ISSUE THREAD

**Issue by WinnieWei0** [nmxiaowei/avue#609]
avue form组件搜索设置行内且设置label在顶部时，操作按钮位置不美观，建议searchMenuPosition增加**top、bottom**，可居上或居下
![image](https://user-images.githubusercontent.com/29709910/230586612-49b3b68d-8cbe-4ff9-884a-006f4fb5d646.png)

版本：
2.9.12

**Comment by nmxiaowei** [comment]
可以用css 全局样式调下

**Comment by nmxiaowei** [comment]
可以用css 全局样式调下
