### ISSUE TITLE
Avue3.x问题反馈专区

### ISSUE THREAD

**Issue by Androidquyi199205270** [nmxiaowei/avue#617]
使用node最新版本，crud组件中option，column配置searchPlaceholder属性不生效

**Comment by nmxiaowei** [comment]
<img width="381" alt="image" src="https://github.com/nmxiaowei/avue/assets/35983068/612edd08-0232-4f3f-bfd5-a3598b187830">
<img width="315" alt="image" src="https://github.com/nmxiaowei/avue/assets/35983068/685010d4-ce22-4226-b1a6-3d526ebe5790">

测试米问题
