### ISSUE TITLE
cropperOption

### ISSUE THREAD

**Issue by ljh257110** [nmxiaowei/avue#619]
图片裁剪相关的配置在avue3没有，现在2的文档也找不着了

**Comment by nmxiaowei** [comment]
v2.avuejs.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nmxiaowei/avue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 下午2:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[nmxiaowei/avue] cropperOption (Issue #619)





 
图片裁剪相关的配置在avue3没有，现在2的文档也找不着了
