### ISSUE TITLE
怎么缓存表格  比如 从表格列表跳到 编辑页 ，编辑完返回上一页 ，表格不会刷新，状态值还在

### ISSUE THREAD

**Issue by ming200825** [nmxiaowei/avue#620]
怎么缓存表格  比如 编辑完返回上一页  ，表格不会刷新

**Comment by ming200825** [comment]
![image](https://github.com/nmxiaowei/avue/assets/4900401/54c395b8-8091-4cb3-8713-69d7b8f0d087)

**Comment by TmRichrd** [comment]
可以使用keep-alive

**Comment by flysnoopycx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!

**Comment by nmxiaowei** [comment]
https://gitee.com/smallweigit/avue-cli
<img width="1313" alt="image" src="https://github.com/nmxiaowei/avue/assets/35983068/56a4853c-7b94-4724-93c1-2d8db423a572">
