### ISSUE TITLE
crud组件的搜索部分 select下拉框设置默认值不起效

### ISSUE THREAD

**Issue by MrWcy** [nmxiaowei/avue#622]
Vue版本：2.6.10
avue版本：2.10.15
问题描述：使用crud组件，设置search为true，类型为select下拉框，下拉框设置value默认值不起效。
代码截图：
![image](https://github.com/nmxiaowei/avue/assets/30768980/fde2ec9b-6397-4074-bbb8-76ffa8853914)
问题截图：
![image](https://github.com/nmxiaowei/avue/assets/30768980/d403673a-0f70-4bdc-bd8c-e501308df25e)

**Comment by nmxiaowei** [comment]
searchValue:xxx
