### ISSUE TITLE
crud组件的表单 select下拉框 searchValue重新赋值不起效

### ISSUE THREAD

**Issue by MrWcy** [nmxiaowei/avue#624]
问题描述：dicData的值是从服务端获取的，我的需求是获取到dicData的值后，select默认选择第一个选项，但是通过代码动态改变searchValue不起效
代码截图: 
![image](https://github.com/nmxiaowei/avue/assets/30768980/63009bef-e9c0-4b78-b979-ecdbb76d77aa)
![image](https://github.com/nmxiaowei/avue/assets/30768980/74fbbd55-da8e-4604-a417-c862ce1eaac9)

**Comment by nmxiaowei** [comment]
<avue-crud :search.sync="search"></avue-crud>

this.search.xx=xxx;

**Comment by MrWcy** [comment]
请问this.search怎么用呀，我打印出来是undefined
![企业微信截图_16917341508059](https://github.com/nmxiaowei/avue/assets/30768980/73669f69-bfe4-42e7-93cb-a0b9f6d2818a)
