### ISSUE TITLE
表格手机端适配问题

### ISSUE THREAD

**Issue by xnng** [nmxiaowei/avue#625]
以下情况都为使用 avue-crud 组件，并且在手机端出现的情况。

版本信息： "@smallwei/avue": "^2.10.15",

 1. 表格会多出一列，所有的表格都会这样，只有手机端会出现这种情况，很奇怪，暂时的解决方案只能将 border 改为 false
 
<img width="467" alt="image" src="https://github.com/nmxiaowei/avue/assets/38936252/5cdd3858-f836-4ed1-a012-fb8fdc4267aa">

配置信息如下：

```js
export default {
  menu: false,
  border: true,
  column: [
    {
      label: '工单编号',
      fixed: "left",
      prop: 'no',
      rules: [
        { max: 100, message: "字符长度不能超过 100", trigger: ['blur', 'change'] }
      ]
    },
  ]
}
```

2. menu 未提供 min-width 属性，menuWidth 在手机端不生效，网格会左右错乱

<img width="740" alt="image" src="https://github.com/nmxiaowei/avue/assets/38936252/11019b96-3a7e-4e46-9384-67f451a65cee">

3. 当添加 size: 'medium' 属性的时候，网格会上下错乱，size 为 mini 时正常。

<img width="674" alt="image" src="https://github.com/nmxiaowei/avue/assets/38936252/663b76c3-7556-45ca-8580-cdc1cecb89d4">

**Comment by nmxiaowei** [comment]
目前在手机端适配不是很完美，只能pad和pc用
