### ISSUE TITLE
el-form的内置ref对象如何获取

### ISSUE THREAD

**Issue by 1441951683** [nmxiaowei/avue#627]
`        this.$refs.form.option.column.filter(item => {
          if (item.prop === "policeId") {
            item.disabled = true;
            console.log(item.disabled);
          }}`
如上代码报"Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'option')"

**Comment by nmxiaowei** [comment]
<avue-form ref="form"></avue-form>
this.$refs.form.$refs.form
