### ISSUE TITLE
关于文档的疑问

### ISSUE THREAD

**Issue by ansonhorse** [nmxiaowei/avue#63]
https://avue.top/doc/crud/crud-search
![image](https://user-images.githubusercontent.com/7548142/59827552-96112300-936b-11e9-8521-3a0f3aa19eb1.png)

请问“以前的用法”，应该在哪里看？

**Comment by ansonhorse** [comment]
https://old.avue.top/
这个链接会重定向到 https://avue.top

**Comment by nmxiaowei** [comment]
参考最新官网例子即可
