### ISSUE TITLE
              disabledDate      设置禁止日期 ，无法生效

### ISSUE THREAD

**Issue by jasonccs** [nmxiaowei/avue#630]
label: '【开始时间-结束时间】',
            prop: 'videoTime',
            type: 'datetimerange',
            format: 'yyyy-MM-dd HH:mm:ss',
            valueFormat: 'yyyy-MM-dd HH:mm:ss',
            rangeSeparator: '至',
            startPlaceholder: '开始日期',
            endPlaceholder: '结束日期',
            defaultTime: ['12:00:00', '12:10:00'],
            span: 20,
            labelWidth: 230,
            disabledDate: function (time) {
              return true
            },   disabledDate（） 
            
            
          设置禁止日期效果  ，无法生效

**Comment by nmxiaowei** [comment]
vue3
https://avuejs.com/form/form-date.html
<img width="502" alt="image" src="https://github.com/nmxiaowei/avue/assets/35983068/a33ea11e-880d-407e-a219-382cfc2c47ec">


vue2
https://v2.avuejs.com/form/form-date.html
<img width="328" alt="image" src="https://github.com/nmxiaowei/avue/assets/35983068/e785abd9-6170-406f-86b5-86887d9fa070">
