### ISSUE TITLE
Time时间组件 配置固定时间范围没生效

### ISSUE THREAD

**Issue by huahaigo** [nmxiaowei/avue#631]
版本：2.8.22

1、这是官网文档的配置
![image](https://github.com/nmxiaowei/avue/assets/69447913/00aec690-a204-4a1b-88c6-49d250a3f8b2)

2、这是我的代码配置 (和官网配置一模一样)
![image](https://github.com/nmxiaowei/avue/assets/69447913/9db0d27c-2f29-4bc3-8961-4e737bdfd464)

3、预期效果
![image](https://github.com/nmxiaowei/avue/assets/69447913/68ab1efe-bc71-471b-950b-ecd9ef468d41)

4、实际界面效果
![image](https://github.com/nmxiaowei/avue/assets/69447913/70dcc07a-5048-4cb1-b40c-c5ce36bd48a0)

**Comment by nmxiaowei** [comment]
需要升级版本 2.10.+
