### ISSUE TITLE
Element-plus 升级 2.4.x 后    avue-curd  搜索框聚焦后回车  会隐藏掉整个搜索框

### ISSUE THREAD

**Issue by Zharlb** [nmxiaowei/avue#636]
错误描述
![image](https://github.com/nmxiaowei/avue/assets/31280968/70e92506-bb7f-4621-8882-1b4c519656f2)
![image](https://github.com/nmxiaowei/avue/assets/31280968/86f956f6-8460-41ff-a181-2ba96babb931)

排查后发现使用了 collapse 组件   element 将折叠按钮元素改为了button   监听了回车事件    导致了上述问题
![image](https://github.com/nmxiaowei/avue/assets/31280968/9acd6d6c-6e04-4472-853f-86f56a78edb3)
![image](https://github.com/nmxiaowei/avue/assets/31280968/266bdba4-799c-4a0f-bdbd-d1a7c9190b8b)

**Comment by nmxiaowei** [comment]
avue升级到最新版本即可
