### ISSUE TITLE
表格新增，tree下拉选择，返回的值是id，展示的是name，怎么获取这个name值

### ISSUE THREAD

**Issue by Lemon-Cai** [nmxiaowei/avue#637]
有人维护吗？帮忙看下这个问题怎么解决

![image](https://github.com/nmxiaowei/avue/assets/37281618/5784b173-2413-48bf-878e-25923c10618f)

![image](https://github.com/nmxiaowei/avue/assets/37281618/0527f059-b7f7-49b5-8059-2b10cd084b97)

ps：没issues，不是好，而是没人用。

**Comment by flysnoopycx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!

**Comment by nmxiaowei** [comment]
v-model绑定的form中 form.$xx
