### ISSUE TITLE
searchFilterable 这个字段想请问文档中在哪有说明

### ISSUE THREAD

**Issue by later-zc** [nmxiaowei/avue#638]
# 环境描述
- avue版本：2.8.26
- 开发框架：vue2
- 系统环境：window
- node版本：14.18.1
- 浏览器环境：Google Chrome 119.0.6045.160（正式版本） （64 位）

# 问题描述
- 在搜索项中，配置了 `searchFilterable` 字段的搜索项是支持下拉输入的
![image](https://github.com/nmxiaowei/avue/assets/50972442/bf04bbee-4d5c-4b63-9fa4-d6f9f0359fc5)
- 但是如下，在相关的新增表单中，该字段项却无法输入搜索词，在下拉框选择项很多的场景下，只能滑动查找对应的选择项，影响使用体验
![image](https://github.com/nmxiaowei/avue/assets/50972442/3c134495-24d2-4833-87a4-cfa9c8f6370e)
- 查阅文档，没找到这个 `searchFilterable` 有关的描述
- 相关的配置代码：
```js 
export const tableOption = {
  // ...
  column: [
    // ...
    {
      label: '项目名称',
      prop: 'stationId',
      // overHidden: true,
      addDisplay: true,
      editDisplay: true,
      editDisabled: true,
      search: true,
      type: 'select',
      searchFilterable: true,
      dicData: store.getters.stations,
      props: {
        label: 'name',
        value: 'stationId',
      },
      formatter: (row) => store.getters.getStationNameById(row.stationId),
      rules: [
        {
          required: true,
          message: '请选择项目名称',
        },
        { validator: checkStation, trigger: 'blur' },
      ],
    }
  ]
}

**Comment by later-zc** [comment]
# 环境描述
- avue版本：2.8.26
- 浏览器环境：Google Chrome 119.0.6045.160（正式版本） （64 位）

# 问题描述
- 在搜索项中，配置了 `searchFilterable` 字段的搜索项是支持下拉输入的
![image](https://github.com/nmxiaowei/avue/assets/50972442/bf04bbee-4d5c-4b63-9fa4-d6f9f0359fc5)
- 但是如下，在相关的新增表单中，该字段项却无法输入搜索词
![image](https://github.com/nmxiaowei/avue/assets/50972442/3c134495-24d2-4833-87a4-cfa9c8f6370e)
- 查阅文档，没找到这个 `searchFilterable` 有关的描述
- 相关的配置代码：
```js 
export const tableOption = {
  // ...
  column: [
    // ...
    {
      label: '项目名称',
      prop: 'stationId',
      // overHidden: true,
      addDisplay: true,
      editDisplay: true,
      editDisabled: true,
      search: true,
      type: 'select',
      searchFilterable: true,
      dicData: store.getters.stations,
      props: {
        label: 'name',
        value: 'stationId',
      },
      formatter: (row) => store.getters.getStationNameById(row.stationId),
      rules: [
        {
          required: true,
          message: '请选择项目名称',
        },
        { validator: checkStation, trigger: 'blur' },
      ],
    }
  ]
}
```js

**Comment by later-zc** [comment]
为什么直接关闭了？

**Comment by later-zc** [comment]
@nmxiaowei 为什么直接关闭了？

**Comment by nmxiaowei** [comment]
表单配置filterable:true
https://v2.avuejs.com/form/form-select.html#%E5%88%9B%E5%BB%BA%E6%9D%A1%E7%9B%AE%E5%92%8C%E6%90%9C%E7%B4%A2

**Comment by later-zc** [comment]
> 表单配置filterable:true https://v2.avuejs.com/form/form-select.html#%E5%88%9B%E5%BB%BA%E6%9D%A1%E7%9B%AE%E5%92%8C%E6%90%9C%E7%B4%A2
filterable 是可以的，

但该链接跳转过去，停留的是首页：
![image](https://github.com/nmxiaowei/avue/assets/50972442/1d8a168e-1dd5-4c6c-b65f-d8d093b28aa7)

而且点击 顶部菜单栏>文档>任意一项（如crud组件），测试效果：无法跳转过去，其他菜单栏跳转正常
