### ISSUE TITLE
vue2 如何开始默认最近三天

### ISSUE THREAD

**Issue by jasonccs** [nmxiaowei/avue#641]
label: '入库时间',
prop: 'updatedTime',
...formType.dateTime,
search: true

**Comment by jasonccs** [comment]
怎么默认选中三天啊
&nbsp;


风起时，想你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月13日(星期三) 上午8:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nmxiaowei/avue] vue2 如何开始默认最近三天 (Issue #641)





 
Closed #641 as completed.

**Comment by nmxiaowei** [comment]
不支持




smallwei
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nmxiaowei/avue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月14日(星期四) 上午8:23
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [nmxiaowei/avue] vue2 如何开始默认最近三天 (Issue #641)





 怎么默认选中三天啊 
 &amp;nbsp; 
 
 
 风起时，想你 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年12月13日(星期三) 上午8:44 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [nmxiaowei/avue] vue2 如何开始默认最近三天 (Issue #641) 
 
 
 
 
 
   
 Closed #641 as completed.

**Comment by jasonccs** [comment]
默认最近三天搜索怎么写啊
&nbsp;


风起时，想你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月14日(星期四) 上午10:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nmxiaowei/avue] vue2 如何开始默认最近三天 (Issue #641)





 不支持 
 
 
 
 
 smallwei 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "nmxiaowei/avue"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年12月14日(星期四) 上午8:23 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [nmxiaowei/avue] vue2 如何开始默认最近三天 (Issue #641) 
 
 
 
 
 
  怎么默认选中三天啊  
  &amp;amp;nbsp;  
   
   
  风起时，想你  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2023年12月13日(星期三) 上午8:44  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [nmxiaowei/avue] vue2 如何开始默认最近三天 (Issue #641)  
   
   
   
   
   
     
  Closed #641 as completed.

**Comment by jasonccs** [comment]
![image](https://github.com/nmxiaowei/avue/assets/17975766/e6449735-b85f-4ffb-8533-09b10bdf4901)
默认最近三天，怎么写

**Comment by ddddssss2022** [comment]
const dateTimeRangeShortcuts = [
    {
        text: '一小时内',
        value: () => {
            return [dayjs().subtract(1, 'hour'), dayjs().endOf('day')];
        }
    },
    {
        text: '今天',
        value: () => {
            return [dayjs().startOf('day'), dayjs().endOf('day')];
        }
    },
    {
        text: '昨天',
        value: () => {
            return [dayjs().subtract(1, 'day').startOf('day'), dayjs().subtract(1, 'day').endOf('day')];
        }
    },
    {
        text: '一周内',
        value: () => {
            return [dayjs().subtract(7, 'day').startOf('day'), dayjs().endOf('day'),];
        },
    },
    {
        text: '一月内',
        value: () => {
            return [dayjs().subtract(30, 'day').startOf('day'), dayjs().endOf('day'),];
        },
    }
];


{
      ...dateTimeRangeColumn,
      prop: "createdAtRange",
      hide: true,
      search: true,
      searchRange: true,
    }
    
    这样实现

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。
