### ISSUE TITLE
表格选择器首次选择问题

### ISSUE THREAD

**Issue by zhuwenbing** [nmxiaowei/avue#642]
你好，最近在使用表格选择器，按照官网的例子改造成查询远程接口后发现，第一次选择后输入框显示的是props的value属性id，props配置如下：
```code
props: {
  label: 'name',
  value: 'id'
}
```
目前的解决办法是拿着这个id再调用一下远程的根据id查询接口，但是感觉这样比较浪费资源。是否有办法通过确定后选中的行获取到这个label属性，或者说获取到选中的整行数据？

**Comment by nmxiaowei** [comment]
目前没有
