### ISSUE TITLE
Avue 引入 并使用发生 TypeError: Cannot read properties of undefined (reading '$el')

### ISSUE THREAD

**Issue by being8000** [nmxiaowei/avue#646]
**版本号**："3.2.8+"
**使用环境**：Vue3, Typescript, setup模式
导入使用异常：
![image](https://github.com/nmxiaowei/avue/assets/40756758/847fa1be-c36f-47a4-9fd3-41fc604f1f14)
![image](https://github.com/nmxiaowei/avue/assets/40756758/e71760a4-cdff-4d68-90b5-7531fe9bd2e3)

**Comment by flysnoopycx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!

**Comment by being8000** [comment]
![image](https://github.com/nmxiaowei/avue/assets/40756758/e0db9dcc-09e7-482a-90b4-e0f0fc23a7e1)
使用了官网的demo

**Comment by nmxiaowei** [comment]
vue版本号多少

**Comment by being8000** [comment]
解决了，需要全局映入Element-Plus
