### ISSUE TITLE
crud tooltip-options的问题

### ISSUE THREAD

**Issue by bigMeowCoding** [nmxiaowei/avue#649]
crud如果我要自定义tooltip，你们有api吗？ 你们目前放在column中的配置是否错误了？
![image](https://github.com/nmxiaowei/avue/assets/24516369/0cf32aa2-0135-494c-b461-19e154f0ed04)
element ui中这个tooltip-options配置是放在table api下不是放在table column下的api，你们这样配置不会生效的

**Comment by nmxiaowei** [comment]
可以用 自定义
https://avuejs.com/crud/crud-column.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97
