### ISSUE TITLE
avue-input-tree多选时，如何实现点击文字区域也可以选中的效果？

### ISSUE THREAD

**Issue by Destini1224** [nmxiaowei/avue#650]
https://avuejs.com/component/input-tree.html
<img width="272" alt="微信图片_20240321160441" src="https://github.com/nmxiaowei/avue/assets/112073014/b15826c9-8d1d-4d19-9d8b-ff40763e6bf2">

**Comment by OakFun** [comment]
请问怎么解决的呢？
