### ISSUE TITLE
使用 inputTabel表格选择器 出现的问题

### ISSUE THREAD

**Issue by xiaozhou1544** [nmxiaowei/avue#651]
1、使用版本 V2
2、使用 inputTabel表格选择器  单组件问题
3、使用官网示例
![image](https://github.com/nmxiaowei/avue/assets/165276681/e347c37e-4769-463f-98da-83e8b2effcb6)
![image](https://github.com/nmxiaowei/avue/assets/165276681/81bb6ec7-68dc-408d-bff5-0aab69066918)
![image](https://github.com/nmxiaowei/avue/assets/165276681/10e34e2b-f0ef-4156-9fc8-ed3377f48881)

**Comment by nmxiaowei** [comment]
更新到 2.11.x

**Comment by xiaozhou1544** [comment]
> 更新到 2.11.x
当前更新到了2.11.2的版本，显示数据问题解决了，但是确认按钮问题并没有解决
![image](https://github.com/nmxiaowei/avue/assets/165276681/8297e325-3562-4af5-8d40-fa9ed86b293f)
![image](https://github.com/nmxiaowei/avue/assets/165276681/9dd19397-0823-46e0-99c7-4e4f073b9397)

![image](https://github.com/nmxiaowei/avue/assets/165276681/0674e016-96d1-4c02-a4a3-2ad931d3d57f)

**Comment by nmxiaowei** [comment]
更新国际化文件 npm

**Comment by xiaozhou1544** [comment]
> 更新国际化文件 npm

谢谢，已经解决了
