### ISSUE TITLE
avue-crud，列表设置高度，同时开启拖拽功能，拖拽的后，列表会重新渲染，自动滚动到顶部，这个能配置修复？

### ISSUE THREAD

**Issue by z-lionel** [nmxiaowei/avue#652]
avue-crud，列表设置高度，同时开启拖拽功能，拖拽列表尾部的数据，
列表会重新渲染，自动滚动到顶部，这个能配置修复？

版本号：
 "@smallwei/avue": "^2.10.4",
Sortable 1.10.0-rc2

**Comment by flysnoopycx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!

**Comment by z-lionel** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!

能解决的吗？

**Comment by nmxiaowei** [comment]
无法修复， ele底层问题
