### ISSUE TITLE
使用ElementPlus的按需导入(自动导入)方法导入ElementPlus组件，而不是全局映射时，该如何配置Vite，还能说是只能使用全局映射的办法才能让Avue正常运行

### ISSUE THREAD

**Issue by github-transition** [nmxiaowei/avue#654]
vite.config.js
![vite](https://github.com/nmxiaowei/avue/assets/79845578/878d2088-7d01-4a8c-aa22-fd48ed3654fa)

按需导入后使用Avue会发生报错(如issues#646)

Avue版本：3.4.2
ELementPlus版本：2.7.3
Vue版本： 3.2.47
Vite版本：4.2.0

**Comment by nmxiaowei** [comment]
必须全局导入才可以
