### ISSUE TITLE
curd设置了分页后页面样式错乱

### ISSUE THREAD

**Issue by fortmin1** [nmxiaowei/avue#655]
代码如下：
![image](https://github.com/nmxiaowei/avue/assets/109221451/7cb153bb-d33b-4806-9717-f2a62916a202)
当total不为0分页栏展示出来时样式错乱，此时数据也展示不出来：
![image](https://github.com/nmxiaowei/avue/assets/109221451/6cb3fe1b-20d7-4823-be6e-2a88dd7b8286)
控制台报错：
![image](https://github.com/nmxiaowei/avue/assets/109221451/c5706b12-f84b-4411-95fc-559c2025e57e)
版本信息：
![image](https://github.com/nmxiaowei/avue/assets/109221451/b6befbb0-8550-45f2-8c59-8ef516cce404)

**Comment by fortmin1** [comment]
已找到问题：
total初始值必须为0，等待表格渲染完再渲染分页内容
![image](https://github.com/nmxiaowei/avue/assets/109221451/8d6fb3c7-a3dc-4464-9d67-998fdceda050)
效果：
![image](https://github.com/nmxiaowei/avue/assets/109221451/bd29f008-a6c2-4872-a226-c10fd9913138)

**Comment by nmxiaowei** [comment]
更新到 3.4.5+
