### ISSUE TITLE
v2更新到最新版本后，图片裁剪用不了

### ISSUE THREAD

**Issue by ml4165837** [nmxiaowei/avue#657]

**Comment by ml4165837** [comment]
固定版本号2.12.4可以使用，升级到2.12.6就不能使用了

**Comment by ml4165837** [comment]
![image](https://github.com/nmxiaowei/avue/assets/4706344/b57cd62a-aee5-4520-908b-428a41a16281)

**Comment by nmxiaowei** [comment]
2.12.7+修复
