### ISSUE TITLE
option index设置true后  page的currentPage不管是多少  序号都是从1开始

### ISSUE THREAD

**Issue by qiming008** [nmxiaowei/avue#658]
@smallwei/avue  2.12.5 和 2.12.6 都是这样     
option index设置true后  page的currentPage不管传的多少  列表序号都是从1开始

**Comment by nmxiaowei** [comment]
2.12.7+修复

**Comment by z-lionel** [comment]
大哥，首页有个问题，能回答下吗？是我提问的方式不对吗？

**Comment by nmxiaowei** [comment]
更新到最新版本，已经修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月11日(周四) 上午10:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [nmxiaowei/avue] option index设置true后  page的currentPage不管是多少  序号都是从1开始 (Issue #658)




 
大哥，首页有个问题，能回答下吗？是我提问的方式不对吗？
