### ISSUE TITLE
v2.12.5之后的版本 水印功能失效了，试了v2.12.5之前的版本正常的

### ISSUE THREAD

**Issue by xiaoxiao-qiang** [nmxiaowei/avue#661]
![111](https://github.com/user-attachments/assets/261ac368-cd45-447e-a524-a26280339e90)

**Comment by nmxiaowei** [comment]
2.12.7+已经修复

**Comment by flysnoopycx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!
