### ISSUE TITLE
crud表格报错 Cannot read properties of undefined (reading 'doLayout')

### ISSUE THREAD

**Issue by zhous1993** [nmxiaowei/avue#668]
crud表格报错 Cannot read properties of undefined (reading 'doLayout')
之前一直都是可以用的，今天安装其他依赖包后出现这个错误，还原后也没有解决
版本：3.4.9
vue版本：3.2.45
![Snipaste_2024-10-11_20-02-16](https://github.com/user-attachments/assets/585cd6ba-a2ed-41ae-82e8-4ba6f3863258)
![Snipaste_2024-10-11_20-40-56](https://github.com/user-attachments/assets/257e2471-c3af-4f29-b253-7cac3270fae6)

**Comment by nmxiaowei** [comment]
更新到3.5+即可解决

**Comment by mack-wang** [comment]
vite升级后，此问题得到了解决。

<img width="1424" alt="Image" src="https://github.com/user-attachments/assets/3f47f3db-74f6-4a26-a900-699bf4720d78" />
