### ISSUE TITLE
更新数据后，数据中的属性 还保留了之前的属性

### ISSUE THREAD

**Issue by OuYangJie167** [nmxiaowei/avue#671]
### 检查清单

- [X] 我已确认当前的 issues 列表中并未有人提出过相同的问题
- [X] 我已确认仓库的 PR 列表中并未有解决该问题的 PR

### 问题描述

更新数据后，数据中的属性 还保留了之前的属性
 
<img width="1874" alt="image" src="https://github.com/user-attachments/assets/d7d8527e-879f-4d5b-8bcf-f8f3803f2501">

### 复现步骤

1. 点击按钮更新数据
界面显示，包含多余的 text2
<img width="1317" alt="image" src="https://github.com/user-attachments/assets/ef5053cb-c633-406c-b25a-fac3f76359a5">

2. 第二次点击，界面显示正确，没有包含多余的属性
<img width="1354" alt="image" src="https://github.com/user-attachments/assets/667996b4-06e8-48f0-a68b-38f8fc5a5182">

因为一些原因，我首次初始化的数据里面可能会有一些多余的属性

### 额外描述
[bind.html.zip](https://github.com/user-attachments/files/17529314/bind.html.zip)

**Comment by OuYangJie167** [comment]
补充版本号: "version": "2.13.1",

**Comment by OuYangJie167** [comment]
大概是这样的场景
我在获取数据后，克隆了一份数据副本数据 用于对比， 但是设置数据后，由于之前有绑定过数据，会导致设置数据后，avue-form 会触发一次更新，将数据进行合并 导致我的数据里面会有多余的属性， 结果 副本数据与设置的数据不同
我或许可以在内部之后保存副本数据， 但是我更希望 新数据里面不包含旧的数据的属性

**Comment by nmxiaowei** [comment]
由于内部一些机制的设置，参数无法去除多余的 只能自己手工去除

**Comment by OuYangJie167** [comment]
> 由于内部一些机制的设置，参数无法去除多余的 只能自己手工去除

@nmxiaowei  我就算 this.form = { } 也会有多余参数   我需要怎么清除， 没有办法重置吗？  设置数据就会发生一次更新 ， 只能在你那次更新之后删除，你的意思是我只能监听你内部的那次修改，然后删除吗
