### ISSUE TITLE
control 控制表单项显隐，在动态修改dicData后失效

### ISSUE THREAD

**Issue by z-lionel** [nmxiaowei/avue#677]
avue-crud通过control控制column里面某个表单项目的显隐，再次外部通过代码直接修改某个表单项的dicData后，control控制的表单项显隐失效

版本2.12.5

{
  label: 'a',
  prop: 'a',
  control: (val) => {
      return:{
          b:{ display: !!val}
      }
  }
},
{
  label: 'b',
  prop: 'b',
  display:false,
  type: 'select',
  dicData: []
},

在页面里面，当a有值的时候，显示b，并设置b的下拉选项，但是设置后，b表单就自动隐藏了，通过打option发现，control
并没有修改option里面的dispaly，因为表单有多个control逻辑，本来通过control控制就可以了，现在修改了dicData的值后，控制
失效，需要在页面把整个逻辑再实现一遍就很复杂了
watch:{
  a:{
      handler(val){
           request().then( res => {
                this.option.column.foreach(item => {
                   if(item.prop == 'b') {  item.dicData = res.data.data } 
                })
           })
      }  
  }
}

**Comment by nmxiaowei** [comment]
修改的值需要提前写到对应的配置项里

**Comment by z-lionel** [comment]
> 修改的值需要提前写到对应的配置项里
这里已经写了，已经都写在修改项里了，还是不行
`{
    label: 'b',
    prop: 'b',
    display:false,
    type: 'select',
    dicData: []
},`

**Comment by z-lionel** [comment]
> 修改的值需要提前写到对应的配置项里

这个已经提前写了，修改的是b项，的display 跟dicData，都已经写在配置项里，还是不行

**Comment by inoryxun** [comment]
> 修改的值需要提前写到对应的配置项里

不单单是修改dicData 一种情况,比如group ,或者其他属性，而且官网这个事例也无效
