### ISSUE TITLE
form 上传组件httpRequest 函数参数文档与实际不符

### ISSUE THREAD

**Issue by inoryxun** [nmxiaowei/avue#678]
![image](https://github.com/user-attachments/assets/058d3b0f-13fe-43d0-896c-d69b27c187ee)
![image](https://github.com/user-attachments/assets/e9c69935-9f1d-4f97-8352-b6c5396f779a)

文档说是会传一个file 文件和当前column ，然而实际是传回了一个request 的请求参数，这个没有实际用处，因为我要自定义上传了，我需要的东西，你的request 里肯定不不支持，因为无法实现动态赋值data

**Comment by nmxiaowei** [comment]
3.6.1+修复

**Comment by flysnoopycx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到了你的邮件!

**Comment by nmxiaowei** [comment]
config中file就是上传文件，可以使用
