### ISSUE TITLE
菜单功能Bug

### ISSUE THREAD

**Issue by Yittang** [nmxiaowei/avue#76]
Bug步骤：
-  添加一级菜单(简称：系统管理)，保存，先给角色勾选菜单查看权限，刷新页面可以看到系统管理菜单。
-  在系统管理菜单内添加二级菜单，保存，去给角色勾选二级菜单查看权限时发现二级菜单**自动**被勾选，刷新页面但左侧菜单栏并没有二级菜单。
- 重新勾选菜单查看权限才可以看到二级菜单。

**Comment by nmxiaowei** [comment]
提交错位置了
