### ISSUE TITLE
如何添加其他城市的地图

### ISSUE THREAD

**Issue by delonhe2812** [nmxiaowei/avue#77]
1、怎么增加新的地图【例如：我怎么添加东莞，中山的地图，可以看到各个街道办或各个区、镇的】？
2、怎么修改地图上一个区域胡背景色（例如广东省的地图，怎么把整个广州市变成红色？)
3、如何高亮显示比如我添加了东莞市的地图后指定的长安镇的某个指标的数据值与镇对应的地图显示对应的值，如：长安镇的2019年7月份的交通违规案件数据量是多少.
4、开发柱状图时发现柱状图下方的文字无法旋转角色将全部X轴或Y轴的主题文字显示全出来，这个要如何调整？
![image](https://user-images.githubusercontent.com/52983919/61340454-fadd7180-a874-11e9-9e06-935222de6f3d.png)

**Comment by nmxiaowei** [comment]
1.通过http://datav.aliyun.com/tools/atlas/#&lat=39.30029918615029&lng=105.99609375&zoom=3网站获取json替换map组件的mapList即可
2.暂时不支持
3.需要通过地图的click事件，完后去刷新需要改变图形的数据
4.可以竖柱状图调节gridX属性距离来显示出来，横柱状图设置xAxisinterval为true全部显示，xAxisRotate旋转的角度

当然你可以用自定义组件实现你的需求
例子:http://data.avue.top/build.html?id=4

**Comment by delonhe2812** [comment]
好的，我按这个尝试一下看看能不能弄出来，谢谢

**Comment by delonhe2812** [comment]
您好，关于第4点，我这边做了几次尝试，发现进行调整这三个参数还是实现不了X轴或Y轴上的主题文字全显示出来，请问是否还需要其他参数配合设置才会生效呢？

**Comment by nmxiaowei** [comment]
更新master最新avue.min.js
