### ISSUE TITLE
关于无法加载广东省地级市城市的各区各镇的子地图问题

### ISSUE THREAD

**Issue by delonhe2812** [nmxiaowei/avue#78]
您好，我使用你们提供的如何添加其他城市的链接地址：http://datav.aliyun.com/tools/atlas/#&lat=33.97980872872457&lng=101.6455078125&zoom=4

1、进行查看了一下发现目前东莞、中山、佛山等城市的行政区的子地图是看不到了，只看到一下大的地级市的地图，其他的省府城市目前看起来是可以看到区域子地图的，发现地图目前是不完善的；
2、请问，中山和东莞的地图预计啥时候才能够进行完善呢？由于我们的生产业务侧的发展需要，我们做数据分析需要做中山和东莞的地图大屏展示。

**Comment by nmxiaowei** [comment]
没有的自行绘制
http://geojson.io/#map=8/37.171/119.048
