### ISSUE TITLE
将avue-data的大屏页面嵌套进第三方平台中时如何实现带上token安全验证

### ISSUE THREAD

**Issue by delonhe2812** [nmxiaowei/avue#80]
目标需求：
我们需要将已开发的avue-data的DEMO页面view.html?id=23嵌套进已有的系统中，需要对权限这一块进行拦截，带有token标识的就允许访问。

现有示例：
例如：我做了如下一个页面DEMO，需要将
http://sinosoft.vicp.io:59144/avuex-data/view.html?id=23 
页面签套进现有的 http://sinosoft.vicp.io:59144/itongde系统中，是否是使用&符号拼接属性的方式将参数据进行传输？如下拼接地址所示：
http://sinosoft.vicp.io:59144/avuex-data/view.html?id=23&token=adfalsdfjdlkjiasidfi

请问，实现的方向是这样子的吗？

**Comment by nmxiaowei** [comment]
在axios拦截器里实现
大屏调用了axios.js
