### ISSUE TITLE
不同的菜单无法使用相同的路由地址

### ISSUE THREAD

**Issue by zhangsenhua** [nmxiaowei/avue#81]
菜单 A 路由地址是 /system/menu?name=A，菜单 B 路由地址是 /system/menu?name=B，点击菜单 A 和菜单 B 会出现 404。
因为 A 和 B 菜单的结构是相同的，而且无法确定当前菜单名称（也可能是 C 或者 D，根据用户添创建菜单的路由地址参数决定的），只能根据路由地址参数 name，向后台发送请求，才能获取相应的信息。所以必须复用同一个 .vue文件，也间接导致两个菜单的路由地址相同，而参数不同的情况。

**Comment by zhangsenhua** [comment]
菜单配置
![image](https://user-images.githubusercontent.com/19898809/61918382-c0b25500-af83-11e9-9a1f-f8517f317f20.png)

**Comment by zhangsenhua** [comment]
浏览器标签页标题 和 TopMenu 标题显示异常

**Comment by zhangsenhua** [comment]
点击菜单浏览器地址变为 /404?name=router 和 /404?name=server

**Comment by leson1986** [comment]
这个问题我也遇到过，我是路由不同，但是组件相同，当pageA正常显示时，pageB一定是404 ，只有刷新了页面，pageB才正常，然而，pageA变成404，反正没有两个是一起成的

**Comment by nmxiaowei** [comment]
提交到avue-cli项目下
