### ISSUE TITLE
关于avuex-data中的散点图坐标轴文字无法显示问题

### ISSUE THREAD

**Issue by delonhe** [nmxiaowei/avue#82]
您好，我在做大屏的过程中由于需要使用到散点图和环形图， 1、在使用过程中发现散点图的坐标轴文字无法正常显示； 2、在使用环形图的过程中想要在环形的中间显示合计的数量值，发现没有相关的属性可以设置出来； 请问这两个问题可以通过怎么设置属性做到显示出来呢？如下截图所示是我开发的应用中显示不出来的效果截图
![开发遇到解决不了的问题](https://user-images.githubusercontent.com/36020237/62180846-eb394f00-b383-11e9-9e4d-6426d57aee0f.png)

**Comment by nmxiaowei** [comment]
到私服avuex-data项目下提交工单
