### ISSUE TITLE
关于合并柱形图的实现

### ISSUE THREAD

**Issue by heroukun** [nmxiaowei/avue#84]
我在开发过程中由于有一个需求需要将多个不同颜色的数据量合并在同一个柱形中，发现现有柱状态图demo不支持，请问有没有相关的实现案例，是怎么实现的？ 如截图所示是我想要实现的柱形图的效果图
![image](https://user-images.githubusercontent.com/44461968/62199986-15f0cb00-b3b7-11e9-8728-369b46985577.png)

**Comment by nmxiaowei** [comment]
c
