### ISSUE TITLE
avue-crud的复杂表头

### ISSUE THREAD

**Issue by zhangyc** [nmxiaowei/avue#87]
采用官网的例子：
avue的版本为2.0.0
代码：
<avue-crud :option="option" :data="data" ></avue-crud>
<script>
export default {
    data() {
      return {
        option: {
          border: true,
          index: true,
          expandLevel: 3,
          headerAlign: 'center',
          align: 'center',
          tree: true,
          labelWidth: 100,
          column: [{
            label: '姓名',
            prop: 'name',
            width:140,
          }, {
            label: '性别1',
            prop: 'sex',
          },
          {
            label: '自定义图标',
            prop: 'icon',
            type: "icon-select",
            iconList: [{
              label: '基本图表',
              list: ['el-icon-time', 'el-icon-bell', 'el-icon-star-on']
            }]
          }, {
            label: '复杂表头',
            children: [{
              label: '信息',
              children: [{
                label: '年龄',
                prop: 'age'
              }, {
                label: '手机号',
                prop: 'phone',
              }]
            }, {
              label: '级别',
              prop: 'grade',
              type: 'select',
              dicData: [{
                label: '测试',
                value: 1
              }]
            }]
          }, {
            label: '测试',
            prop: 'test',
          },
          {
            label: '手机信息1',
            prop: 'phone1'
          }],
        },
        data: [{
          name: '张三',
          age: 14,
          grade: 1,
          phone1: '17547400800',
          phone: '17547400800',
          icon: 'el-icon-time',
          test: 1,
          sex: '男'
        }, {
          name: '王五',
          age: 10,
          grade: 1,
          test: 1,
          sex: '女',
          icon: 'el-icon-star-on',
          phone1: '17547400800',
          phone: '17547400800'
        }]
      }
    }
}
</script>
报错：
error.js?c738:20 TypeError: Cannot set property 'columnBtn' of undefined
    at avue.min.js:159
    at Array.forEach (<anonymous>)
    at c (avue.min.js:159)
    at VueComponent.columnInit (avue.min.js:159)
    at VueComponent.boundFn [as columnInit] (vue.min.js:193)
    at VueComponent.columnOption (avue.min.js:125)
    at Watcher.run (vue.min.js:3126)
    at flushSchedulerQueue (vue.min.js:2880)
    at Array.<anonymous> (vue.min.js:1789)
    at flushCallbacks (vue.min.js:1710)

**Comment by nmxiaowei** [comment]
无法复现
