### ISSUE TITLE
关于Flow流程组件获取option值的问题

### ISSUE THREAD

**Issue by m442428915** [nmxiaowei/avue#95]
Flow 流程组件，在绘制完流程图后，想获取option中的数据，nodeList里的left 和top 还有lineList，现在获取不到里面的数据，请帮忙解决一下，谢谢！
![Uploading image.png…]()
{"name":"流程A","nodeList":[{"id":"node0","name":"开始节点","left":0,"top":0},{"id":"node1","name":"你好","left":0,"top":0},{"id":"node2","name":"你好1","left":0,"top":0}],"lineList":[]}

**Comment by nmxiaowei** [comment]
已修复，下个版本更新
