### ISSUE TITLE
CRUD中使用富文本编辑器组件无法上传图片

### ISSUE THREAD

**Issue by hongzhw** [nmxiaowei/avue#97]
![image](https://user-images.githubusercontent.com/21365611/64306896-dbd2a480-cfc6-11e9-9937-5c1d48454df5.png)

![image](https://user-images.githubusercontent.com/21365611/64306980-19373200-cfc7-11e9-8e37-f54aae57d31e.png)

富文本编辑器在CRUD中如上图使用，获取不到action的图片上传地址

**Comment by nmxiaowei** [comment]
自行查看例子demo
